//
//  FlightAirportDbMockData.swift
//  taillog
//
//  Created by Shubham Tiwari on 31/07/24.
//

import Foundation
class FlightAirportDbMockData{
    static let mockData = [
        FlightAirportDB(
            id: 49,
                flight_id: 500000,
                descriptions: "Departure",
                type: "DEP",
                route_description: nil,
                route_distance: nil,
                icao: "WIII",
                iata: "CGK",
                name: "JAKARTA/SOEKARN",
                elev: 34,
                rwy_planned: nil,
                rwyl_planned: nil,
                fac_planned: nil,
                rvr_planned: nil,
                ceil_planned: nil,
                rwy: nil,
                rwyl: nil,
                braking_action: nil,
                fac: nil,
                wv_w: nil,
                wv_v: nil,
                gust: nil,
                visibility: nil,
                rvr: nil,
                ceil: nil,
                temperature: nil,
                dewpoint: nil,
                qnh: nil,
                lat: -6.12361097,
                lon: 106.66110229,
                runways: "[{name: 06, length: 9843}, {name: 07L, length: 11811}, {name: 07R, length: 12008}, {name: 24, length: 9843}, {name: 25L, length: 12008}, {name: 25R, length: 11811}]",
                atis_string: "",
                atis_json: nil,
                metar: "140600Z  VRB05KT 9000 SCT020 31/25 Q1009 NOSIG=",
                taf_type: "FT",
                taf_text: "140500Z  1406/1512 06010KT 7000 SCT020 TEMPO 1409/1412 5000 -TSRA FEW018CB BECMG 1412/1414 17005KT 5000 HZ="
        ),
        
        FlightAirportDB(
            id: 50,
            flight_id: 500000,
            descriptions: "Arrival",
            type: "ARR",
            route_description: nil,
            route_distance: 493,
            icao: "WSSS",
            iata: "SIN",
            name: "SINGAPORE/CHANG",
            elev: 22,
            rwy_planned: nil,
            rwyl_planned: nil,
            fac_planned: nil,
            rvr_planned: nil,
            ceil_planned: nil,
            rwy: nil,
            rwyl: nil,
            braking_action: nil,
            fac: nil,
            wv_w: nil,
            wv_v: nil,
            gust: nil,
            visibility: nil,
            rvr: nil,
            ceil: nil,
            temperature: nil,
            dewpoint: nil,
            qnh: nil,
            lat: 1.35921097,
            lon: 103.98930359,
            runways: "[{\"name\": \"02C\", \"length\": 13123}, {\"name\": \"02L\", \"length\": 13123}, {\"name\": \"02R\", \"length\": 13123}, {\"name\": \"20C\", \"length\": 13123}, {\"name\": \"20L\", \"length\": 13123}, {\"name\": \"20R\", \"length\": 13123}]",
            atis_string: "",
            atis_json: nil,
            metar: "140600Z  19006KT 140V210 9999 FEW018 FEW020CB SCT180 30/24 Q1008 NOSIG=",
            taf_type: "FT",
            taf_text: "140500Z  1406/1512 20007KT 9999 FEW015 SCT020 TEMPO 1500/1503 3000 TSRA FEW012CB BKN015="
        ),

        FlightAirportDB(
            id: 51,
            flight_id: 500000,
            descriptions: "Alternate 1",
            type: "ALT1",
            route_description: "SEL",
            route_distance: 33,
            icao: "WSSL",
            iata: "XSP",
            name: "SINGAPORE/SELET",
            elev: 46,
            rwy_planned: nil,
            rwyl_planned: nil,
            fac_planned: nil,
            rvr_planned: nil,
            ceil_planned: nil,
            rwy: nil,
            rwyl: nil,
            braking_action: nil,
            fac: nil,
            wv_w: nil,
            wv_v: nil,
            gust: nil,
            visibility: nil,
            rvr: nil,
            ceil: nil,
            temperature: nil,
            dewpoint: nil,
            qnh: nil,
            lat: 1.41695595,
            lon: 103.86759949,
            runways: "[{\"name\": \"03\", \"length\": 6024}, {\"name\": \"21\", \"length\": 6024}]",
            atis_string: "",
            atis_json: nil,
            metar: "140600Z  21006KT 160V300 9999 FEW020 FEW022CB BKN300 31/23 Q1008=",
            taf_type: "FT",
            taf_text: "140500Z  1406/1512 20007KT 9999 FEW015 SCT020 TEMPO 1500/1503 3000 TSRA FEW012CB BKN015="
        ),

        FlightAirportDB(
            id: 52,
            flight_id: 500001,
            descriptions: "Departure",
            type: "DEP",
            route_description: nil,
            route_distance: nil,
            icao: "VTBS",
            iata: "BKK",
            name: "BANGKOK/SUVARNA",
            elev: 5,
            rwy_planned: nil,
            rwyl_planned: nil,
            fac_planned: nil,
            rvr_planned: nil,
            ceil_planned: nil,
            rwy: nil,
            rwyl: nil,
            braking_action: nil,
            fac: nil,
            wv_w: nil,
            wv_v: nil,
            gust: nil,
            visibility: nil,
            rvr: nil,
            ceil: nil,
            temperature: nil,
            dewpoint: nil,
            qnh: nil,
            lat: 13.68583012,
            lon: 100.74890137,
            runways: "[{\"name\": \"01L\", \"length\": 12139}, {\"name\": \"01R\", \"length\": 13123}, {\"name\": \"19L\", \"length\": 13123}, {\"name\": \"19R\", \"length\": 12139}]",
            atis_string: "",
            atis_json: nil,
            metar: "300930Z  26004KT 9000 VCSH FEW020CB SCT040 32/22 Q1006 NOSIG=",
            taf_type: "FT",
            taf_text: "300500Z  3006/3112 16005KT 9999 FEW020 TEMPO 3008/3012 VRB15KT 4000 TSRA FEW018CB SCT030 BKN100 BECMG 3100/3102 22008KT TEMPO 3108/3112 VRB15KT 4000 TSRA FEW018CB SCT030 BKN100="
        ),

        FlightAirportDB(
            id: 53,
            flight_id: 500001,
            descriptions: "Arrival",
            type: "ARR",
            route_description: nil,
            route_distance: 655,
            icao: "VVNB",
            iata: "HAN",
            name: "HA NOI/NOI BAI",
            elev: 43,
            rwy_planned: nil,
            rwyl_planned: nil,
            fac_planned: nil,
            rvr_planned: nil,
            ceil_planned: nil,
            rwy: nil,
            rwyl: nil,
            braking_action: nil,
            fac: nil,
            wv_w: nil,
            wv_v: nil,
            gust: nil,
            visibility: nil,
            rvr: nil,
            ceil: nil,
            temperature: nil,
            dewpoint: nil,
            qnh: nil,
            lat: 21.22167015,
            lon: 105.80560303,
            runways: "[{\"name\": \"11L\", \"length\": 10499}, {\"name\": \"11R\", \"length\": 12467}, {\"name\": \"29L\", \"length\": 12467}, {\"name\": \"29R\", \"length\": 10499}]",
            atis_string: "",
            atis_json: nil,
            metar: "300930Z  08006KT 050V120 CAVOK 35/25 Q1005 NOSIG=",
            taf_type: "FT",
            taf_text: "300500Z  3006/3106 14007KT 9999 SCT027 BECMG 3022/3023 4000 BR BECMG 3101/3102 8000 NSW="
        ),

        FlightAirportDB(
            id: 54,
            flight_id: 500001,
            descriptions: "Alternate 1",
            type: "ALT1",
            route_description: "DCT",
            route_distance: 888,
            icao: "RCPO",
            iata: "HSZ",
            name: "HSINCHU",
            elev: 26,
            rwy_planned: nil,
            rwyl_planned: nil,
            fac_planned: nil,
            rvr_planned: nil,
            ceil_planned: nil,
            rwy: nil,
            rwyl: nil,
            braking_action: nil,
            fac: nil,
            wv_w: nil,
            wv_v: nil,
            gust: nil,
            visibility: nil,
            rvr: nil,
            ceil: nil,
            temperature: nil,
            dewpoint: nil,
            qnh: nil,
            lat: 24.81999969,
            lon: 120.94170380,
            runways: "[{\"name\": \"05\", \"length\": 12014}, {\"name\": \"23\", \"length\": 12014}]",
            atis_string: "",
            atis_json: nil,
            metar: "",
            taf_type: "",
            taf_text: ""
        ),

        FlightAirportDB(
            id: 55,
            flight_id: 500003,
            descriptions: "Departure",
            type: "DEP",
            route_description: nil,
            route_distance: nil,
            icao: "EKRK",
            iata: "RKE",
            name: "COPENHAGEN/ROSK",
            elev: 146,
            rwy_planned: nil,
            rwyl_planned: nil,
            fac_planned: nil,
            rvr_planned: nil,
            ceil_planned: nil,
            rwy: nil,
            rwyl: nil,
            braking_action: nil,
            fac: nil,
            wv_w: nil,
            wv_v: nil,
            gust: nil,
            visibility: nil,
            rvr: nil,
            ceil: nil,
            temperature: nil,
            dewpoint: nil,
            qnh: nil,
            lat: 55.58557129,
            lon: 12.13142967,
            runways: "[{\"name\": \"03\", \"length\": 4921}, {\"name\": \"11\", \"length\": 5902}, {\"name\": \"21\", \"length\": 4921}, {\"name\": \"29\", \"length\": 5902}]",
            atis_string: "",
            atis_json: nil,
            metar: "020650Z  AUTO 31003KT 9999 NCD 16/11 Q1023=",
            taf_type: "FT",
            taf_text: "020503Z  0206/0215 VRB02KT CAVOK BECMG 0210/0212 12012KT="
        ),

        FlightAirportDB(
            id: 57,
            flight_id: 500003,
            descriptions: "Arrival",
            type: "ARR",
            route_description: nil,
            route_distance: 111,
            icao: "EKBI",
            iata: "BLL",
            name: "BILLUND",
            elev: 247,
            rwy_planned: nil,
            rwyl_planned: nil,
            fac_planned: nil,
            rvr_planned: nil,
            ceil_planned: nil,
            rwy: nil,
            rwyl: nil,
            braking_action: nil,
            fac: nil,
            wv_w: nil,
            wv_v: nil,
            gust: nil,
            visibility: nil,
            rvr: nil,
            ceil: nil,
            temperature: nil,
            dewpoint: nil,
            qnh: nil,
            lat: 55.74031830,
            lon: 9.15177822,
            runways: "[{\"name\": \"09\", \"length\": 10171}, {\"name\": \"27\", \"length\": 10171}]",
            atis_string: "",
            atis_json: nil,
            metar: "020650Z  AUTO 13002KT 9999 NCD 15/08 Q1023=",
            taf_type: "FT",
            taf_text: "020503Z  0206/0306 VRB02KT CAVOK BECMG 0209/0212 10012KT="
        ),

        FlightAirportDB(
            id: 59,
            flight_id: 500003,
            descriptions: "Alternate 1",
            type: "ALT1",
            route_description: "GIGUT DCT ABINO",
            route_distance: 85,
            icao: "EKAH",
            iata: "AAR",
            name: "AARHUS",
            elev: 82,
            rwy_planned: nil,
            rwyl_planned: nil,
            fac_planned: nil,
            rvr_planned: nil,
            ceil_planned: nil,
            rwy: nil,
            rwyl: nil,
            braking_action: nil,
            fac: nil,
            wv_w: nil,
            wv_v: nil,
            gust: nil,
            visibility: nil,
            rvr: nil,
            ceil: nil,
            temperature: nil,
            dewpoint: nil,
            qnh: nil,
            lat: 56.30001831,
            lon: 10.61900997,
            runways: "[{\"name\": \"10L\", \"length\": 9111}, {\"name\": \"10R\", \"length\": 8865}, {\"name\": \"28L\", \"length\": 8865}, {\"name\": \"28R\", \"length\": 9111}]",
            atis_string: "",
            atis_json: nil,
            metar: "020650Z  AUTO 00000KT 9999 SCT068/// 14/12 Q1023=",
            taf_type: "FT",
            taf_text: "020503Z  0206/0306 VRB02KT CAVOK BECMG 0209/0212 11012KT="
        ),

        FlightAirportDB(
            id: 61,
            flight_id: 500004,
            descriptions: "Departure",
            type: "DEP",
            route_description: nil,
            route_distance: nil,
            icao: "EKRK",
            iata: "RKE",
            name: "COPENHAGEN/ROSK",
            elev: 146,
            rwy_planned: nil,
            rwyl_planned: nil,
            fac_planned: nil,
            rvr_planned: nil,
            ceil_planned: nil,
            rwy: nil,
            rwyl: nil,
            braking_action: nil,
            fac: nil,
            wv_w: nil,
            wv_v: nil,
            gust: nil,
            visibility: nil,
            rvr: nil,
            ceil: nil,
            temperature: nil,
            dewpoint: nil,
            qnh: nil,
            lat: 55.58557129,
            lon: 12.13142967,
            runways: "[{\"name\": \"03\", \"length\": 4921}, {\"name\": \"11\", \"length\": 5902}, {\"name\": \"21\", \"length\": 4921}, {\"name\": \"29\", \"length\": 5902}]",
            atis_string: "",
            atis_json: nil,
            metar: "020550Z  AUTO 32001KT 9999 NCD 12/11 Q1023=",
            taf_type: "FT",
            taf_text: "020503Z  0206/0215 VRB02KT CAVOK BECMG 0210/0212 12012KT="
        ),

        FlightAirportDB(
            id: 62,
            flight_id: 500004,
            descriptions: "Arrival",
            type: "ARR",
            route_description: nil,
            route_distance: 111,
            icao: "EKBI",
            iata: "BLL",
            name: "BILLUND",
            elev: 247,
            rwy_planned: nil,
            rwyl_planned: nil,
            fac_planned: nil,
            rvr_planned: nil,
            ceil_planned: nil,
            rwy: nil,
            rwyl: nil,
            braking_action: nil,
            fac: nil,
            wv_w: nil,
            wv_v: nil,
            gust: nil,
            visibility: nil,
            rvr: nil,
            ceil: nil,
            temperature: nil,
            dewpoint: nil,
            qnh: nil,
            lat: 55.74031830,
            lon: 9.15177822,
            runways: "[{\"name\": \"09\", \"length\": 10171}, {\"name\": \"27\", \"length\": 10171}]",
            atis_string: "",
            atis_json: nil,
            metar: "020550Z  AUTO 08002KT 9999 NCD 09/08 Q1023=",
            taf_type: "FT",
            taf_text: "020503Z  0206/0306 VRB02KT CAVOK BECMG 0209/0212 10012KT="
        ),

        FlightAirportDB(
            id: 63,
            flight_id: 500004,
            descriptions: "Alternate 1",
            type: "ALT1",
            route_description: "GIGUT DCT ABINO",
            route_distance: 85,
            icao: "EKAH",
            iata: "AAR",
            name: "AARHUS",
            elev: 82,
            rwy_planned: nil,
            rwyl_planned: nil,
            fac_planned: nil,
            rvr_planned: nil,
            ceil_planned: nil,
            rwy: nil,
            rwyl: nil,
            braking_action: nil,
            fac: nil,
            wv_w: nil,
            wv_v: nil,
            gust: nil,
            visibility: nil,
            rvr: nil,
            ceil: nil,
            temperature: nil,
            dewpoint: nil,
            qnh: nil,
            lat: 56.30001831,
            lon: 10.61900997,
            runways: "[{\"name\": \"10L\", \"length\": 9111}, {\"name\": \"10R\", \"length\": 8865}, {\"name\": \"28L\", \"length\": 8865}, {\"name\": \"28R\", \"length\": 9111}]",
            atis_string: "",
            atis_json: nil,
            metar: "020550Z  AUTO 27001KT 9999 BKN060/// 12/11 Q1023=",
            taf_type: "FT",
            taf_text: "020503Z  0206/0306 VRB02KT CAVOK BECMG 0209/0212 11012KT="
        ),
        
        FlightAirportDB(
            id: 73,
            flight_id: 500002,
            descriptions: "Departure",
            type: "DEP",
            route_description: nil,
            route_distance: nil,
            icao: "EKRK",
            iata: "RKE",
            name: "COPENHAGEN/ROSK",
            elev: 146,
            rwy_planned: nil,
            rwyl_planned: nil,
            fac_planned: nil,
            rvr_planned: nil,
            ceil_planned: nil,
            rwy: nil,
            rwyl: nil,
            braking_action: nil,
            fac: nil,
            wv_w: nil,
            wv_v: nil,
            gust: nil,
            visibility: nil,
            rvr: nil,
            ceil: nil,
            temperature: nil,
            dewpoint: nil,
            qnh: nil,
            lat: 55.58557129,
            lon: 12.13142967,
            runways: "[{\"name\": \"03\", \"length\": 4921}, {\"name\": \"11\", \"length\": 5902}, {\"name\": \"21\", \"length\": 4921}, {\"name\": \"29\", \"length\": 5902}]",
            atis_string: "",
            atis_json: nil,
            metar: "020950Z  AUTO VRB03KT 9999 FEW047/// 19/07 Q1023=",
            taf_type: "FT",
            taf_text: "020806Z  0209/0218 VRB02KT CAVOK BECMG 0210/0212 12012KT="
        ),

        FlightAirportDB(
            id: 74,
            flight_id: 500002,
            descriptions: "Arrival",
            type: "ARR",
            route_description: nil,
            route_distance: 111,
            icao: "EKBI",
            iata: "BLL",
            name: "BILLUND",
            elev: 247,
            rwy_planned: nil,
            rwyl_planned: nil,
            fac_planned: nil,
            rvr_planned: nil,
            ceil_planned: nil,
            rwy: nil,
            rwyl: nil,
            braking_action: nil,
            fac: nil,
            wv_w: nil,
            wv_v: nil,
            gust: nil,
            visibility: nil,
            rvr: nil,
            ceil: nil,
            temperature: nil,
            dewpoint: nil,
            qnh: nil,
            lat: 55.74031830,
            lon: 9.15177822,
            runways: "[{\"name\": \"09\", \"length\": 10171}, {\"name\": \"27\", \"length\": 10171}]",
            atis_string: "",
            atis_json: nil,
            metar: "020950Z  AUTO 08007KT 9999 BKN068/// 18/09 Q1023=",
            taf_type: "FT",
            taf_text: "020503Z  0206/0306 VRB02KT CAVOK BECMG 0209/0212 10012KT="
        ),

        FlightAirportDB(
            id: 75,
            flight_id: 500002,
            descriptions: "Alternate 1",
            type: "ALT1",
            route_description: "GIGUT DCT ABINO",
            route_distance: 85,
            icao: "EKAH",
            iata: "AAR",
            name: "AARHUS",
            elev: 82,
            rwy_planned: nil,
            rwyl_planned: nil,
            fac_planned: nil,
            rvr_planned: nil,
            ceil_planned: nil,
            rwy: nil,
            rwyl: nil,
            braking_action: nil,
            fac: nil,
            wv_w: nil,
            wv_v: nil,
            gust: nil,
            visibility: nil,
            rvr: nil,
            ceil: nil,
            temperature: nil,
            dewpoint: nil,
            qnh: nil,
            lat: 56.30001831,
            lon: 10.61900997,
            runways: "[{\"name\": \"10L\", \"length\": 9111}, {\"name\": \"10R\", \"length\": 8865}, {\"name\": \"28L\", \"length\": 8865}, {\"name\": \"28R\", \"length\": 9111}]",
            atis_string: "",
            atis_json: nil,
            metar: "020950Z  AUTO 10006KT 080V170 9999 BKN037/// BKN061/// 19/10 Q1023=",
            taf_type: "FT",
            taf_text: "020503Z  0206/0306 VRB02KT CAVOK BECMG 0209/0212 11012KT="
        ),

        FlightAirportDB(
            id: 76,
            flight_id: 500005,
            descriptions: "Departure",
            type: "DEP",
            route_description: nil,
            route_distance: nil,
            icao: "EKCH",
            iata: "CPH",
            name: "COPENHAGEN/KAST",
            elev: 17,
            rwy_planned: nil,
            rwyl_planned: nil,
            fac_planned: nil,
            rvr_planned: nil,
            ceil_planned: nil,
            rwy: nil,
            rwyl: nil,
            braking_action: nil,
            fac: nil,
            wv_w: nil,
            wv_v: nil,
            gust: nil,
            visibility: nil,
            rvr: nil,
            ceil: nil,
            temperature: nil,
            dewpoint: nil,
            qnh: nil,
            lat: 55.61791992,
            lon: 12.65596962,
            runways: "[{\"name\": \"04L\", \"length\": 11811}, {\"name\": \"04R\", \"length\": 10827}, {\"name\": \"12\", \"length\": 9186}, {\"name\": \"22L\", \"length\": 10827}, {\"name\": \"22R\", \"length\": 11811}, {\"name\": \"30\", \"length\": 9186}]",
            atis_string: "",
            atis_json: nil,
            metar: "050850Z  AUTO 12013KT 9999 NCD 19/10 Q1030 NOSIG=",
            taf_type: "FT",
            taf_text: "050500Z  0506/0606 10012KT CAVOK TEMPO 0510/0515 13015G25KT="
        ),

        FlightAirportDB(
            id: 77,
            flight_id: 500005,
            descriptions: "Arrival",
            type: "ARR",
            route_description: nil,
            route_distance: 409,
            icao: "EPMO",
            iata: "WMI",
            name: "WARSAW/MODLIN",
            elev: 344,
            rwy_planned: nil,
            rwyl_planned: nil,
            fac_planned: nil,
            rvr_planned: nil,
            ceil_planned: nil,
            rwy: nil,
            rwyl: nil,
            braking_action: nil,
            fac: nil,
            wv_w: nil,
            wv_v: nil,
            gust: nil,
            visibility: nil,
            rvr: nil,
            ceil: nil,
            temperature: nil,
            dewpoint: nil,
            qnh: nil,
            lat: 52.45111084,
            lon: 20.65193939,
            runways: "[{\"name\": \"08\", \"length\": 8202}, {\"name\": \"26\", \"length\": 8202}]",
            atis_string: "",
            atis_json: nil,
            metar: "050900Z  09005KT 010V140 CAVOK 18/04 Q1029 =",
            taf_type: "FT",
            taf_text: "050530Z  0506/0606 07008KT CAVOK="
        ),

        FlightAirportDB(
            id: 78,
            flight_id: 500005,
            descriptions: "Alternate 1",
            type: "ALT1",
            route_description: "DCT",
            route_distance: 46,
            icao: "EPWA",
            iata: "WAW",
            name: "WARSAW/CHOPIN",
            elev: 362,
            rwy_planned: nil,
            rwyl_planned: nil,
            fac_planned: "B : Basic / NDB",
            rvr_planned: nil,
            ceil_planned: nil,
            rwy: nil,
            rwyl: nil,
            braking_action: nil,
            fac: nil,
            wv_w: nil,
            wv_v: nil,
            gust: nil,
            visibility: nil,
            rvr: nil,
            ceil: nil,
            temperature: nil,
            dewpoint: nil,
            qnh: nil,
            lat: 52.16582870,
            lon: 20.96722031,
            runways: "[{\"name\": \"11\", \"length\": 9186}, {\"name\": \"15\", \"length\": 12106}, {\"name\": \"29\", \"length\": 9186}, {\"name\": \"33\", \"length\": 12106}]",
            atis_string: "",
            atis_json: nil,
            metar: "050900Z  VRB06KT CAVOK 19/03 Q1029 NOSIG=",
            taf_type: "FT",
            taf_text: "050830Z  0509/0609 07008KT CAVOK="
        ),

        FlightAirportDB(
            id: 79,
            flight_id: 500006,
            descriptions: "Departure",
            type: "DEP",
            route_description: nil,
            route_distance: nil,
            icao: "EKCH",
            iata: "CPH",
            name: "COPENHAGEN/KAST",
            elev: 17,
            rwy_planned: nil,
            rwyl_planned: nil,
            fac_planned: nil,
            rvr_planned: nil,
            ceil_planned: nil,
            rwy: nil,
            rwyl: nil,
            braking_action: nil,
            fac: nil,
            wv_w: nil,
            wv_v: nil,
            gust: nil,
            visibility: nil,
            rvr: nil,
            ceil: nil,
            temperature: nil,
            dewpoint: nil,
            qnh: nil,
            lat: 55.61791992,
            lon: 12.65596962,
            runways: "[{\"name\": \"04L\", \"length\": 11811}, {\"name\": \"04R\", \"length\": 10827}, {\"name\": \"12\", \"length\": 9186}, {\"name\": \"22L\", \"length\": 10827}, {\"name\": \"22R\", \"length\": 11811}, {\"name\": \"30\", \"length\": 9186}]",
            atis_string: "",
            atis_json: nil,
            metar: "280520Z  AUTO 21005KT 9999 NCD 12/11 Q1017 nosig=",
            taf_type: "FT",
            taf_text: "272321Z  2800/2824 17010KT 9000 NSC BECMG 2804/2806 23010KT PROB40 2805/2812 2000 BR BKN004 BECMG 2812/2814 16006KT BECMG 2822/2824 4000 BR BKN008="
        ),

        FlightAirportDB(
            id: 80,
            flight_id: 500006,
            descriptions: "Arrival",
            type: "ARR",
            route_description: nil,
            route_distance: 4322,
            icao: "KO47",
            iata: nil,
            name: "PRAGUE MUNI",
            elev: 1041,
            rwy_planned: nil,
            rwyl_planned: nil,
            fac_planned: nil,
            rvr_planned: nil,
            ceil_planned: nil,
            rwy: nil,
            rwyl: nil,
            braking_action: nil,
            fac: nil,
            wv_w: nil,
            wv_v: nil,
            gust: nil,
            visibility: nil,
            rvr: nil,
            ceil: nil,
            temperature: nil,
            dewpoint: nil,
            qnh: nil,
            lat: 35.48078156,
            lon: -96.71875000,
            runways: "[{\"name\": \"17\", \"length\": 3600}, {\"name\": \"35\", \"length\": 3600}]",
            atis_string: "",
            atis_json: nil,
            metar: "",
            taf_type: "",
            taf_text: ""
        ),

        FlightAirportDB(
            id: 81,
            flight_id: 500006,
            descriptions: "Alternate 1",
            type: "ALT1",
            route_description: "DCT",
            route_distance: 38,
            icao: "KSRE",
            iata: nil,
            name: "SEMINOLE MUNI",
            elev: 1023,
            rwy_planned: nil,
            rwyl_planned: nil,
            fac_planned: nil,
            rvr_planned: nil,
            ceil_planned: nil,
            rwy: nil,
            rwyl: nil,
            braking_action: nil,
            fac: nil,
            wv_w: nil,
            wv_v: nil,
            gust: nil,
            visibility: nil,
            rvr: nil,
            ceil: nil,
            temperature: nil,
            dewpoint: nil,
            qnh: nil,
            lat: 35.27445984,
            lon: -96.67537689,
            runways: "[{\"name\": \"03\", \"length\": 2000}, {\"name\": \"16\", \"length\": 5004}, {\"name\": \"21\", \"length\": 2000}, {\"name\": \"34\", \"length\": 5004}]",
            atis_string: "",
            atis_json: nil,
            metar: "280515Z  AUTO 11004KT 10SM FEW019 OVC080 14/05 A3009 RMK AO2=",
            taf_type: "",
            taf_text: ""
        ),

        FlightAirportDB(
            id: 82,
            flight_id: 500007,
            descriptions: "Departure",
            type: "DEP",
            route_description: nil,
            route_distance: nil,
            icao: "LLBG",
            iata: "TLV",
            name: "TEL AVIV/BEN GU",
            elev: 134,
            rwy_planned: nil,
            rwyl_planned: nil,
            fac_planned: nil,
            rvr_planned: nil,
            ceil_planned: nil,
            rwy: nil,
            rwyl: nil,
            braking_action: nil,
            fac: nil,
            wv_w: nil,
            wv_v: nil,
            gust: nil,
            visibility: nil,
            rvr: nil,
            ceil: nil,
            temperature: nil,
            dewpoint: nil,
            qnh: nil,
            lat: 32.00944138,
            lon: 34.88555908,
            runways: "[{\"name\": \"03\", \"length\": 9094}, {\"name\": \"08\", \"length\": 13327}, {\"name\": \"12\", \"length\": 10210}, {\"name\": \"21\", \"length\": 9094}, {\"name\": \"26\", \"length\": 13327}, {\"name\": \"30\", \"length\": 10210}]",
            atis_string: "",
            atis_json: nil,
            metar: "280520Z  VRB02KT CAVOK 20/17 Q1016 NOSIG=",
            taf_type: "FT",
            taf_text: "280506Z  2806/2906 VRB03KT 9999 FEW020 BECMG 2807/2809 31010KT CAVOK BECMG 2815/2817 VRB03KT 9999 FEW015 PROB40 TEMPO 2823/2906 8000 BKN012 TX28/2811Z TN18/2904Z="
        ),

        FlightAirportDB(
            id: 83,
            flight_id: 500007,
            descriptions: "Arrival",
            type: "ARR",
            route_description: nil,
            route_distance: 247,
            icao: "LCLK",
            iata: "LCA",
            name: "LARNAKA INTL",
            elev: 11,
            rwy_planned: nil,
            rwyl_planned: nil,
            fac_planned: nil,
            rvr_planned: nil,
            ceil_planned: nil,
            rwy: nil,
            rwyl: nil,
            braking_action: nil,
            fac: nil,
            wv_w: nil,
            wv_v: nil,
            gust: nil,
            visibility: nil,
            rvr: nil,
            ceil: nil,
            temperature: nil,
            dewpoint: nil,
            qnh: nil,
            lat: 34.87889099,
            lon: 33.63027954,
            runways: "[{\"name\": \"04\", \"length\": 9823}, {\"name\": \"22\", \"length\": 9823}]",
            atis_string: "",
            atis_json: nil,
            metar: "280500Z  29005KT CAVOK 19/12 Q1017 NOSIG=",
            taf_type: "FT",
            taf_text: "280530Z  2806/2906 32006KT 9999 FEW025 BECMG 2807/2810 04012KT BECMG 2816/2819 32006KT="
        ),

        FlightAirportDB(
            id: 84,
            flight_id: 500007,
            descriptions: "Alternate 1",
            type: "ALT1",
            route_description: "DCT LCA DCT",
            route_distance: 43,
            icao: "LCEN",
            iata: "ECN",
            name: "LEFKOSA / ERCAN",
            elev: 402,
            rwy_planned: nil,
            rwyl_planned: nil,
            fac_planned: nil,
            rvr_planned: nil,
            ceil_planned: nil,
            rwy: nil,
            rwyl: nil,
            braking_action: nil,
            fac: nil,
            wv_w: nil,
            wv_v: nil,
            gust: nil,
            visibility: nil,
            rvr: nil,
            ceil: nil,
            temperature: nil,
            dewpoint: nil,
            qnh: nil,
            lat: 35.14889145,
            lon: 33.49972153,
            runways: "[{\"name\": \"11\", \"length\": 9039}, {\"name\": \"29\", \"length\": 9039}]",
            atis_string: "",
            atis_json: nil,
            metar: "280520Z  27008KT CAVOK 18/11 Q1017 NOSIG=",
            taf_type: "FT",
            taf_text: "280440Z  2806/2906 08015KT 9999 FEW025 PROB30 TEMPO 2811/2815 BKN025 BECMG 2816/2818 29012KT="
        ),

        FlightAirportDB(
            id: 88,
            flight_id: 500008,
            descriptions: "Departure",
            type: "DEP",
            route_description: nil,
            route_distance: nil,
            icao: "EKCH",
            iata: "CPH",
            name: "COPENHAGEN/KAST",
            elev: 17,
            rwy_planned: nil,
            rwyl_planned: nil,
            fac_planned: nil,
            rvr_planned: nil,
            ceil_planned: nil,
            rwy: nil,
            rwyl: nil,
            braking_action: nil,
            fac: nil,
            wv_w: nil,
            wv_v: nil,
            gust: nil,
            visibility: nil,
            rvr: nil,
            ceil: nil,
            temperature: nil,
            dewpoint: nil,
            qnh: nil,
            lat: 55.61791992,
            lon: 12.65596962,
            runways: "[{\"name\": \"04L\", \"length\": 11811}, {\"name\": \"04R\", \"length\": 10827}, {\"name\": \"12\", \"length\": 9186}, {\"name\": \"22L\", \"length\": 10827}, {\"name\": \"22R\", \"length\": 11811}, {\"name\": \"30\", \"length\": 9186}]",
            atis_string: "",
            atis_json: nil,
            metar: "280950Z  AUTO 21005KT 9999 NCD 16/14 Q1018 nosig=",
            taf_type: "FT",
            taf_text: "280754Z  AMD 2808/2906 17005KT 9999 SCT030 BECMG 2822/2901 23010KT 3000 -RADZ BR BKN006 BECMG 2901/2903 29016KT 9999 NSW SCT012="
        ),

        FlightAirportDB(
            id: 89,
            flight_id: 500008,
            descriptions: "Arrival",
            type: "ARR",
            route_description: nil,
            route_distance: 4322,
            icao: "KO47",
            iata: nil,
            name: "PRAGUE MUNI",
            elev: 1041,
            rwy_planned: nil,
            rwyl_planned: nil,
            fac_planned: nil,
            rvr_planned: nil,
            ceil_planned: nil,
            rwy: nil,
            rwyl: nil,
            braking_action: nil,
            fac: nil,
            wv_w: nil,
            wv_v: nil,
            gust: nil,
            visibility: nil,
            rvr: nil,
            ceil: nil,
            temperature: nil,
            dewpoint: nil,
            qnh: nil,
            lat: 35.48078156,
            lon: -96.71875000,
            runways: "[{\"name\": \"17\", \"length\": 3600}, {\"name\": \"35\", \"length\": 3600}]",
            atis_string: "",
            atis_json: nil,
            metar: "",
            taf_type: "",
            taf_text: ""
        )
    ]
    
}
