//
//  FlightDbMockData.swift
//  taillog
//
//  Created by Shubham Tiwari on 31/07/24.
//

import Foundation

class FlightDbMockData{
    static let mockData = [
        FlightsDB(
            id: 500000,
            operator_id: 1,
            user_id: 2985,
            pps: "{\"data\": {\"version\": 0, \"flight_id\": 33588316, \"pps_account\": \"PINTOMAP\", \"flight_remark\": \"\", \"flight_log_name\": \"PM1BANO-WIII-WSSS\", \"external_flight_id\": \"\"}, \"account\": {\"username\": \"pm1morten\", \"third_party_system\": \"Crew Briefing\"}}",
            number: "PM1BANO",
            dep: "WIII",
            dep_iata: "CGK",
            dest: "WSSS",
            dest_iata: "SIN",
            std: DateTimeFunctions.stringToDate("2022-07-14 14:03:00") ?? Date(),
            sta: nil,
            prepared_at: DateTimeFunctions.stringToDate("2022-06-13 07:58:20") ?? Date(),
            aircraft_id: 76,
            aircraft_registration: "TAILNO",
            aircraft_type: "FA8X",
            revised: false,
            status: "Complete",
            uuid: "1a0872af-e668-4c95-b749-bfe3ff937b02",
            flight_type: "LRC",
            uom_altitude: "ft",
            uom_distance: "nm",
            uom_length: "m",
            uom_moment_arm: "in",
            uom_volume: "l",
            uom_weight: "lb",
            uom_pressure: "hpa",
            uom_speed: "kt",
            uom_vertical_speed: "ftpmin",
            uom_flow: "lbph",
            uom_temperature: "c",
            uom_fuel_density: "kgpl",
            trip_number: "",
            ofp_type: "NORMAL",
            archived_at: nil,
            deleted_at: nil,
            created_at: DateTimeFunctions.stringToDate("2022-06-14 00:58:40") ?? nil,
            updated_at: DateTimeFunctions.stringToDate("2022-07-14 14:52:36") ?? nil,
            edited_at: DateTimeFunctions.stringToDate("2022-07-14 14:52:36") ?? Date()
        ),
        FlightsDB(
            id: 500001,
            operator_id: 1,
            user_id: 2985,
            pps: "{\"data\": {\"version\": 0, \"flight_id\": 34262373, \"pps_account\": \"PINTOMAP\", \"flight_remark\": \"\", \"flight_log_name\": \"PM1BAMBOO-VTBS-VVNB\", \"external_flight_id\": \"\"}, \"account\": {\"username\": \"pm1morten\", \"third_party_system\": \"Crew Briefing\"}}",
            number: "PM1BAMBOO",
            dep: "VTBS",
            dep_iata: "BKK",
            dest: "VVNB",
            dest_iata: "HAN",
            std: DateTimeFunctions.stringToDate("2022-08-30 09:00:00") ?? Date(),
            sta: nil,
            prepared_at: DateTimeFunctions.stringToDate("2022-08-30 07:03:04") ?? Date(),
            aircraft_id: 76,
            aircraft_registration: "BANO",
            aircraft_type: "FA8X",
            revised: false,
            status: "Complete",
            uuid: "5b12ec76-8a66-4243-a2f3-b8931f94e9cb",
            flight_type: "LRC",
            uom_altitude: "ft",
            uom_distance: "nm",
            uom_length: "m",
            uom_moment_arm: "in",
            uom_volume: "l",
            uom_weight: "lb",
            uom_pressure: "hpa",
            uom_speed: "kt",
            uom_vertical_speed: "ftpmin",
            uom_flow: "lbph",
            uom_temperature: "c",
            uom_fuel_density: "kgpl",
            trip_number: "",
            ofp_type: "",
            archived_at: nil,
            deleted_at: nil,
            created_at: DateTimeFunctions.stringToDate("2022-09-02 00:27:27") ?? nil,
            updated_at: DateTimeFunctions.stringToDate("2022-09-02 00:28:33") ?? nil,
            edited_at: DateTimeFunctions.stringToDate("2022-09-02 00:28:33") ?? Date()
        ),
        FlightsDB(
            id: 500002,
            operator_id: 1,
            user_id: 2985,
            pps: "{\"data\": {\"version\": 0, \"flight_id\": 34281598, \"pps_account\": \"PINTOMAP\", \"flight_remark\": \"\", \"flight_log_name\": \"PM1RPA-EKRK-EKBI\", \"external_flight_id\": \"\"}, \"account\": {\"username\": \"pm1morten\", \"third_party_system\": \"Crew Briefing\"}}",
            number: "PM1RPA",
            dep: "EKRK",
            dep_iata: "RKE",
            dest: "EKBI",
            dest_iata: "BLL",
            std: DateTimeFunctions.stringToDate("2022-09-01 11:00:00") ?? Date(),
            sta: nil,
            prepared_at: DateTimeFunctions.stringToDate("2022-09-01 09:41:19") ?? Date(),
            aircraft_id: 76,
            aircraft_registration: "BANO",
            aircraft_type: "FA8X",
            revised: false,
            status: "Complete",
            uuid: "5ebda19c-6e8e-4647-9db9-44b760d0552c",
            flight_type: "LRC",
            uom_altitude: "ft",
            uom_distance: "nm",
            uom_length: "m",
            uom_moment_arm: "in",
            uom_volume: "l",
            uom_weight: "lb",
            uom_pressure: "hpa",
            uom_speed: "kt",
            uom_vertical_speed: "ftpmin",
            uom_flow: "lbph",
            uom_temperature: "c",
            uom_fuel_density: "kgpl",
            trip_number: "",
            ofp_type: "",
            archived_at: nil,
            deleted_at: nil,
            created_at: DateTimeFunctions.stringToDate("2022-09-02 04:53:23") ?? nil,
            updated_at: DateTimeFunctions.stringToDate("2022-09-02 04:53:23") ?? nil,
            edited_at: DateTimeFunctions.stringToDate("2022-09-02 04:53:23") ?? Date()
        ),
        FlightsDB(
            id: 500003,
            operator_id: 1,
            user_id: 2985,
            pps: "{\"data\": {\"version\": 0, \"flight_id\": 34281598, \"pps_account\": \"PINTOMAP\", \"flight_remark\": \"\", \"flight_log_name\": \"PM1RPA-EKRK-EKBI\", \"external_flight_id\": \"\"}, \"account\": {\"username\": \"pm1morten\", \"third_party_system\": \"Crew Briefing\"}}",
            number: "PM1RPA",
            dep: "EKRK",
            dep_iata: "RKE",
            dest: "EKBI",
            dest_iata: "BLL",
            std: DateTimeFunctions.stringToDate("2022-09-01 11:00:00") ?? Date(),
            sta: nil,
            prepared_at: DateTimeFunctions.stringToDate("2022-09-01 09:41:19") ?? Date(),
            aircraft_id: 76,
            aircraft_registration: "BANO",
            aircraft_type: "FA8X",
            revised: false,
            status: "Complete",
            uuid: "4d6ee716-c357-42f0-b07d-a3743a7859b8",
            flight_type: "LRC",
            uom_altitude: "ft",
            uom_distance: "nm",
            uom_length: "m",
            uom_moment_arm: "in",
            uom_volume: "l",
            uom_weight: "lb",
            uom_pressure: "hpa",
            uom_speed: "kt",
            uom_vertical_speed: "ftpmin",
            uom_flow: "lbph",
            uom_temperature: "c",
            uom_fuel_density: "kgpl",
            trip_number: "",
            ofp_type: "",
            archived_at: nil,
            deleted_at: nil,
            created_at: DateTimeFunctions.stringToDate("2022-09-02 01:54:12") ?? nil,
            updated_at: DateTimeFunctions.stringToDate("2022-09-02 01:54:12") ?? nil,
            edited_at: DateTimeFunctions.stringToDate("2022-09-02 01:54:12") ?? Date()
        ),
        FlightsDB(
                id: 500004,
                operator_id: 1,
                user_id: 2985,
                pps: "{\"data\": {\"version\": 0, \"flight_id\": 34281598, \"pps_account\": \"PINTOMAP\", \"flight_remark\": \"\", \"flight_log_name\": \"PM1RPA-EKRK-EKBI\", \"external_flight_id\": \"\"}, \"account\": {\"username\": \"pm1morten\", \"third_party_system\": \"Crew Briefing\"}}",
                number: "PM1RPA",
                dep: "EKRK",
                dep_iata: "RKE",
                dest: "EKBI",
                dest_iata: "BLL",
                std: DateTimeFunctions.stringToDate("2022-09-01 11:00:00") ?? Date(),
                sta: nil,
                prepared_at: DateTimeFunctions.stringToDate("2022-09-01 09:41:19") ?? Date(),
                aircraft_id: 76,
                aircraft_registration: "BANO",
                aircraft_type: "FA8X",
                revised: false,
                status: "Complete",
                uuid: "aaec6ed5-b5fe-4e09-97aa-4fc41243402b",
                flight_type: "LRC",
                uom_altitude: "ft",
                uom_distance: "nm",
                uom_length: "m",
                uom_moment_arm: "in",
                uom_volume: "l",
                uom_weight: "lb",
                uom_pressure: "hpa",
                uom_speed: "kt",
                uom_vertical_speed: "ftpmin",
                uom_flow: "lbph",
                uom_temperature: "c",
                uom_fuel_density: "kgpl",
                trip_number: "",
                ofp_type: "NORMAL",
                archived_at: nil,
                deleted_at: nil,
                created_at: DateTimeFunctions.stringToDate("2022-09-02 00:57:28") ?? nil,
                updated_at: DateTimeFunctions.stringToDate("2022-09-02 00:57:29") ?? nil,
                edited_at: DateTimeFunctions.stringToDate("2022-09-02 00:57:29") ?? Date()
            ),
            FlightsDB(
                id: 500005,
                operator_id: 1,
                user_id: 2985,
                pps: "{\"data\": {\"version\": 0, \"flight_id\": 34313480, \"pps_account\": \"PINTOMAP\", \"flight_remark\": \"\", \"flight_log_name\": \"PM1BANO-EKCH-EPMO\", \"external_flight_id\": \"\"}, \"account\": {\"username\": \"pm1morten\", \"third_party_system\": \"Crew Briefing\"}}",
                number: "PM1BANO",
                dep: "EKCH",
                dep_iata: "CPH",
                dest: "EPMO",
                dest_iata: "WMI",
                std: DateTimeFunctions.stringToDate("2022-09-05 07:00:00") ?? Date(),
                sta: nil,
                prepared_at: DateTimeFunctions.stringToDate("2022-09-05 06:46:54") ?? Date(),
                aircraft_id: 76,
                aircraft_registration: "BANO",
                aircraft_type: "FA8X",
                revised: false,
                status: "Complete",
                uuid: "b9c8225b-f939-4494-96f0-f29578759669",
                flight_type: "LRC",
                uom_altitude: "ft",
                uom_distance: "nm",
                uom_length: "m",
                uom_moment_arm: "in",
                uom_volume: "l",
                uom_weight: "lb",
                uom_pressure: "hpa",
                uom_speed: "kt",
                uom_vertical_speed: "ftpmin",
                uom_flow: "lbph",
                uom_temperature: "c",
                uom_fuel_density: "kgpl",
                trip_number: "",
                ofp_type: "",
                archived_at: nil,
                deleted_at: nil,
                created_at: DateTimeFunctions.stringToDate("2022-09-05 03:58:53") ?? nil,
                updated_at: DateTimeFunctions.stringToDate("2022-09-05 03:58:53") ?? nil,
                edited_at: DateTimeFunctions.stringToDate("2022-09-05 03:58:53") ?? Date()
            ),
            FlightsDB(
                id: 500006,
                operator_id: 1,
                user_id: 2985,
                pps: "{\"data\": {\"version\": 0, \"flight_id\": 34748590, \"pps_account\": \"PINTOMAP\", \"flight_remark\": \"\", \"flight_log_name\": \"PM1BANO-EKCH-KO47\", \"external_flight_id\": \"\"}, \"account\": {\"username\": \"pm1morten\", \"third_party_system\": \"Crew Briefing\"}}",
                number: "PM1BANO",
                dep: "EKCH",
                dep_iata: "CPH",
                dest: "KO47",
                dest_iata: "",
                std: DateTimeFunctions.stringToDate("2022-10-27 12:00:00") ?? Date(),
                sta: nil,
                prepared_at: DateTimeFunctions.stringToDate("2022-10-27 07:21:26") ?? Date(),
                aircraft_id: 9,
                aircraft_registration: "SSNTPL",
                aircraft_type: "FA8X",
                revised: false,
                status: "Complete",
                uuid: "02dc4d86-5000-4596-952b-136246f741dc",
                flight_type: "NAT HLA",
                uom_altitude: "ft",
                uom_distance: "nm",
                uom_length: "m",
                uom_moment_arm: "in",
                uom_volume: "l",
                uom_weight: "lb",
                uom_pressure: "hpa",
                uom_speed: "kt",
                uom_vertical_speed: "ftpmin",
                uom_flow: "lbph",
                uom_temperature: "c",
                uom_fuel_density: "kgpl",
                trip_number: "",
                ofp_type: "NORMAL",
                archived_at: nil,
                deleted_at: nil,
                created_at: DateTimeFunctions.stringToDate("2022-10-28 00:03:35") ?? nil,
                updated_at: DateTimeFunctions.stringToDate("2022-10-28 00:03:35") ?? nil,
                edited_at: DateTimeFunctions.stringToDate("2022-10-28 00:03:35") ?? Date()
            ),
            FlightsDB(
                id: 500007,
                operator_id: 1,
                user_id: 2985,
                pps: "{\"data\": {\"version\": 0, \"flight_id\": 34748762, \"pps_account\": \"PINTOMAP\", \"flight_remark\": \"\", \"flight_log_name\": \"PM1LONO-LLBG-LCLK\", \"external_flight_id\": \"\"}, \"account\": {\"username\": \"pm1morten\", \"third_party_system\": \"Crew Briefing\"}}",
                number: "PM1LONO",
                dep: "LLBG",
                dep_iata: "TLV",
                dest: "LCLK",
                dest_iata: "LCA",
                std: DateTimeFunctions.stringToDate("2022-10-27 09:00:00") ?? Date(),
                sta: nil,
                prepared_at: DateTimeFunctions.stringToDate("2022-10-27 07:48:37") ?? Date(),
                aircraft_id: 9,
                aircraft_registration: "SSNTPL",
                aircraft_type: "A332",
                revised: false,
                status: "Complete",
                uuid: "4a389e63-7691-4e70-8f24-0ed792f17d95",
                flight_type: "LRC",
                uom_altitude: "ft",
                uom_distance: "nm",
                uom_length: "m",
                uom_moment_arm: "in",
                uom_volume: "l",
                uom_weight: "lb",
                uom_pressure: "hpa",
                uom_speed: "kt",
                uom_vertical_speed: "ftpmin",
                uom_flow: "lbph",
                uom_temperature: "c",
                uom_fuel_density: "kgpl",
                trip_number: "",
                ofp_type: "NORMAL",
                archived_at: nil,
                deleted_at: nil,
                created_at: DateTimeFunctions.stringToDate("2022-10-28 00:07:54") ?? nil,
                updated_at: DateTimeFunctions.stringToDate("2022-10-28 00:07:54") ?? nil,
                edited_at: DateTimeFunctions.stringToDate("2022-10-28 00:07:54") ?? Date()
            ),
        FlightsDB(
            id: 500022,
            operator_id: 1,
            user_id: 2985,
            pps: "{\"account\":{\"username\":\"GSW7194\",\"third_party_system\":\"Crew Briefing\"},\"data\":{\"flight_id\":38210895,\"version\":0,\"pps_account\":\"ASISTIM GSW\",\"flight_log_name\":\"GM602(2KP)-ZRH-PRN\",\"flight_remark\":\"\",\"external_flight_id\":\"\"}}",
            number: "GM602(2KP)",
            dep: "LSZH",
            dep_iata: "ZRH",
            dest: "BKPR",
            dest_iata: "PRN",
            std: DateTimeFunctions.stringToDate("2024-02-20 17:42:00") ?? Date(),
            sta: DateTimeFunctions.stringToDate("2024-02-20 19:15:00") ?? Date(),
            prepared_at: DateTimeFunctions.stringToDate("2024-02-12 10:56:05") ?? Date(),
            aircraft_id: 76,
            aircraft_registration: "OEFZC",
            aircraft_type: "A320",
            revised: false,
            status: "Complete",
            uuid: "3185bf24-b492-471c-8ca3-265f30cf0257",
            flight_type: "",
            uom_altitude: "ft",
            uom_distance: "nm",
            uom_length: "m",
            uom_moment_arm: "in",
            uom_volume: "l",
            uom_weight: "lb",
            uom_pressure: "hpa",
            uom_speed: "kt",
            uom_vertical_speed: "ftpmin",
            uom_flow: "lbph",
            uom_temperature: "c",
            uom_fuel_density: "kgpl",
            trip_number: "",
            ofp_type: "NORMAL",
            archived_at: nil,
            deleted_at: nil,
            created_at: DateTimeFunctions.stringToDate("2024-02-12 13:38:59") ?? nil,
            updated_at: DateTimeFunctions.stringToDate("2024-02-10 13:45:59") ?? nil,
            edited_at: DateTimeFunctions.stringToDate("2024-02-10 13:45:59") ?? Date()
        ),

        FlightsDB(
            id: 500023,
            operator_id: 1,
            user_id: 2985,
            pps: "{\"account\":{\"username\":\"GSW7194\",\"third_party_system\":\"Crew Briefing\"},\"data\":{\"flight_id\":38210895,\"version\":0,\"pps_account\":\"ASISTIM GSW\",\"flight_log_name\":\"GM602(2KP)-ZRH-PRN\",\"flight_remark\":\"\",\"external_flight_id\":\"\"}}",
            number: "GM602(2KP)",
            dep: "LSZH",
            dep_iata: "ZRH",
            dest: "BKPR",
            dest_iata: "PRN",
            std: DateTimeFunctions.stringToDate("2024-02-20 17:43:00") ?? Date(),
            sta: DateTimeFunctions.stringToDate("2024-02-20 19:15:00") ?? Date(),
            prepared_at: DateTimeFunctions.stringToDate("2024-02-12 10:56:05") ?? Date(),
            aircraft_id: 76,
            aircraft_registration: "OEFZC",
            aircraft_type: "A320",
            revised: false,
            status: "Complete",
            uuid: "a37b8ece-6ff9-4cda-be0c-2a76d0d1693b",
            flight_type: "",
            uom_altitude: "ft",
            uom_distance: "nm",
            uom_length: "m",
            uom_moment_arm: "in",
            uom_volume: "l",
            uom_weight: "lb",
            uom_pressure: "hpa",
            uom_speed: "kt",
            uom_vertical_speed: "ftpmin",
            uom_flow: "lbph",
            uom_temperature: "c",
            uom_fuel_density: "kgpl",
            trip_number: "",
            ofp_type: "NORMAL",
            archived_at: nil,
            deleted_at: nil,
            created_at: DateTimeFunctions.stringToDate("2024-02-12 13:38:59") ?? nil,
            updated_at: DateTimeFunctions.stringToDate("2024-02-10 13:45:59") ?? nil,
            edited_at: DateTimeFunctions.stringToDate("2024-02-10 13:45:59") ?? Date()
        ),
        FlightsDB(
        id: 500024,
        operator_id: 1,
        user_id: 2985,
        pps: "{\"account\":{\"username\":\"GSW7194\",\"third_party_system\":\"Crew Briefing\"},\"data\":{\"flight_id\":38210895,\"version\":0,\"pps_account\":\"ASISTIM GSW\",\"flight_log_name\":\"GM602(2KP)-ZRH-PRN\",\"flight_remark\":\"\",\"external_flight_id\":\"\"}}"
,
        number: "GM602(2KP)",
        dep: "LSZH",
        dep_iata: "ZRH",
        dest: "BKPR",
        dest_iata: "PRN",
        std: DateTimeFunctions.stringToDate("2024-02-20 17:44:00") ?? Date(),
        sta: DateTimeFunctions.stringToDate("2024-02-20 19:15:00") ?? Date(),
        prepared_at: DateTimeFunctions.stringToDate("2024-02-12 10:56:05") ?? Date(),
        aircraft_id: 76,
        aircraft_registration: "OEFZC",
        aircraft_type: "A320",
        revised: false,
        status: "Complete",
        uuid: "15dcb71f-d532-4501-9dc8-5746f5a3d552",
        flight_type: "",
        uom_altitude: "ft",
        uom_distance: "nm",
        uom_length: "m",
        uom_moment_arm: "in",
        uom_volume: "l",
        uom_weight: "lb",
        uom_pressure: "hpa",
        uom_speed: "kt",
        uom_vertical_speed: "ftpmin",
        uom_flow: "lbph",
        uom_temperature: "c",
        uom_fuel_density: "kgpl",
        trip_number: "",
        ofp_type: "NORMAL",
        archived_at: nil,
        deleted_at: nil,
        created_at: DateTimeFunctions.stringToDate("2024-02-12 13:38:59") ?? nil,
        updated_at: DateTimeFunctions.stringToDate("2024-02-10 13:45:59") ?? nil,
        edited_at: DateTimeFunctions.stringToDate("2024-02-10 13:45:59") ?? Date()
        ),
        
        FlightsDB(
        id: 500025,
        operator_id: 1,
        user_id: 2985,
        pps: "{\"account\":{\"username\":\"GSW7194\",\"third_party_system\":\"Crew Briefing\"},\"data\":{\"flight_id\":38210895,\"version\":0,\"pps_account\":\"ASISTIM GSW\",\"flight_log_name\":\"GM602(2KP)-ZRH-PRN\",\"flight_remark\":\"\",\"external_flight_id\":\"\"}}",
        number: "GM602(2KP)",
        dep: "LSZH",
        dep_iata: "ZRH",
        dest: "BKPR",
        dest_iata: "PRN",
        std: DateTimeFunctions.stringToDate("2024-02-20 17:45:00") ?? Date(),
        sta: DateTimeFunctions.stringToDate("2024-02-20 19:15:00") ?? Date(),
        prepared_at: DateTimeFunctions.stringToDate("2024-02-12 10:56:05") ?? Date(),
        aircraft_id: 76,
        aircraft_registration: "OEFZC",
        aircraft_type: "A320",
        revised: false,
        status: "Complete",
        uuid: "df93c4f4-4436-4a40-8bc9-f724a2e615b0",
        flight_type: "",
        uom_altitude: "ft",
        uom_distance: "nm",
        uom_length: "m",
        uom_moment_arm: "in",
        uom_volume: "l",
        uom_weight: "lb",
        uom_pressure: "hpa",
        uom_speed: "kt",
        uom_vertical_speed: "ftpmin",
        uom_flow: "lbph",
        uom_temperature: "c",
        uom_fuel_density: "kgpl",
        trip_number: "",
        ofp_type: "NORMAL",
        archived_at: nil,
        deleted_at: nil,
        created_at: DateTimeFunctions.stringToDate("2024-02-12 13:38:59") ?? nil,
        updated_at: DateTimeFunctions.stringToDate("2024-02-10 13:45:59") ?? nil,
        edited_at: DateTimeFunctions.stringToDate("2024-02-10 13:45:59") ?? Date()
        )
    ]

    
    }
