//
//  FlightWaypointsDbMockData.swift
//  taillog
//
//  Created by Shubham Tiwari on 31/07/24.
//

import Foundation

class FlightWaypointsDbMockData{
    static let mockData = [
        FlightWaypointsDB(
                id: 193,
                flight_id: 500000,
                wp_id: 1000,
                status: 1,
                route: 16,
                type: 1,
                fir_1: "",
                fir_2: "",
                airway: "",
                variation: 1,
                magnetic_track: 0,
                true_track: 0,
                distance_leg: 0,
                distance_accumulated: 0,
                distance_remaining: 493,
                position_ident_1: "WIII",
                position_ident_2: "",
                position_type: "",
                position_frequency: 2.23,
                time_leg: 123,
                time_accumulated: 0,
                time_remaining: 0,
                eto: DateTimeFunctions.stringToDate("2022-06-14 06:28:21") ?? nil,
                reto:DateTimeFunctions.stringToDate("2022-06-14 06:28:21") ?? nil,
                ato: DateTimeFunctions.stringToDate("2022-06-14 06:28:21") ?? nil,
                fl: 380,
                climb_descent: nil,
                mora: 0,
                tas: 0,
                gs: 0,
                wv_w: 0,
                wv_v: 0,
                wv_wc_dir: "H",
                wv_wc_qty: 0,
                wv_cat: 0,
                sat: 0,
                isa_data: -61,
                temperature: 0,
                fuel_flow: -56,
                fuel_flow_eng: 0,
                fuel_leg: 0,
                fuel_used_accumulated: 0,
                fuel_rem: 0,
                fuel_rem_ind: 0,
                fuel_rem_calc: 0,
                fuel_req_min: 0,
                lat: -6.12360001,
                lon: 106.66110229,
                remarks: "",
                meta: "[]",
                landing_time: DateTimeFunctions.stringToDate("1970-01-01 00:00:00") ?? nil,
                engine_off_time:DateTimeFunctions.stringToDate("1970-01-01 00:00:00") ?? nil,
                engine_on_time: DateTimeFunctions.stringToDate("1970-01-01 00:00:00") ?? nil,
                pax: nil,
                pax_weight: nil,
                cargo_weight: nil,
                landing_fuel: nil,
                uplift_fuel: nil
        ),
        
        FlightWaypointsDB(
                id: 194,
                flight_id: 500000,
                wp_id: 2001,
                status: 1,
                route: 16,
                type: 16384,
                fir_1: "",
                fir_2: "",
                airway: "",
                variation: 0,
                magnetic_track: 323,
                true_track: 324,
                distance_leg: 61,
                distance_accumulated: 61,
                distance_remaining: 432,
                position_ident_1: "-TOC-",
                position_ident_2: "",
                position_type: "",
                position_frequency: nil,
                time_leg: 10,
                time_accumulated: 10,
                time_remaining: 72,
                eto: DateTimeFunctions.stringToDate("2022-06-14 06:38:21") ?? nil,
                reto: DateTimeFunctions.stringToDate("2022-06-14 06:38:21") ?? nil,
                ato: DateTimeFunctions.stringToDate("2022-06-14 06:28:21") ?? nil,
                fl: 380,
                climb_descent: nil,
                mora: 119,
                tas: 378,
                gs: 378,
                wv_w: 55,
                wv_v: 23,
                wv_wc_dir: "H",
                wv_wc_qty: 0,
                wv_cat: 0,
                sat: -61,
                isa_data: 0,
                temperature: -56,
                fuel_flow: 1608,
                fuel_flow_eng: 804,
                fuel_leg: 0,
                fuel_used_accumulated: 1019,
                fuel_rem: 3200,
                fuel_rem_ind: nil,
                fuel_rem_calc: nil,
                fuel_req_min: 3065,
                lat: -5.30429983,
                lon: 106.05619812,
                remarks: "",
                meta: "[]",
                landing_time: DateTimeFunctions.stringToDate("1970-01-01 00:00:00") ?? nil,
                engine_off_time: DateTimeFunctions.stringToDate("1970-01-01 00:00:00") ?? nil,
                engine_on_time: DateTimeFunctions.stringToDate("1970-01-01 00:00:00") ?? nil,
                pax: nil,
                pax_weight: nil,
                cargo_weight: nil,
                landing_fuel: nil,
                uplift_fuel: nil
            ),
        
            FlightWaypointsDB(
                id: 195,
                flight_id: 500000,
                wp_id: 3002,
                status: 1,
                route: 16,
                type: 0,
                fir_1: "WI",
                fir_2: "WIIF",
                airway: "DOLT2K",
                variation: 0,
                magnetic_track: 323,
                true_track: 324,
                distance_leg: 17,
                distance_accumulated: 78,
                distance_remaining: 415,
                position_ident_1: "DOLTA",
                position_ident_2: "DOLTA",
                position_type: "A",
                position_frequency: nil,
                time_leg: 4,
                time_accumulated: 14,
                time_remaining: 68,
                eto: DateTimeFunctions.stringToDate("2022-06-14 06:42:21") ?? nil,
                reto: DateTimeFunctions.stringToDate("2022-06-14 06:42:21") ?? nil,
                ato: DateTimeFunctions.stringToDate("2022-06-14 06:28:21") ?? nil,
                fl: 380,
                climb_descent: nil,
                mora: 75,
                tas: 378,
                gs: 378,
                wv_w: 56,
                wv_v: 22,
                wv_wc_dir: "H",
                wv_wc_qty: 0,
                wv_cat: 0,
                sat: -61,
                isa_data: 0,
                temperature: -56,
                fuel_flow: 1608,
                fuel_flow_eng: 804,
                fuel_leg: 0,
                fuel_used_accumulated: 1091,
                fuel_rem: 3127,
                fuel_rem_ind: 3128,
                fuel_rem_calc: 2992,
                fuel_req_min: 123,
                lat: -5.12610006,
                lon: 105.92489624,
                remarks: "",
                meta: "[]",
                landing_time: DateTimeFunctions.stringToDate("1970-01-01 00:00:00") ?? nil,
                engine_off_time: DateTimeFunctions.stringToDate("1970-01-01 00:00:00") ?? nil,
                engine_on_time: DateTimeFunctions.stringToDate("1970-01-01 00:00:00") ?? nil,
                pax: nil,
                pax_weight: nil,
                cargo_weight: nil,
                landing_fuel: nil,
                uplift_fuel: nil
            ),
        
            FlightWaypointsDB(
                id: 196,
                flight_id: 500000,
                wp_id: 4003,
                status: 1,
                route: 16,
                type: 0,
                fir_1: "WI",
                fir_2: "WIIF",
                airway: "W12",
                variation: 0,
                magnetic_track: 330,
                true_track: 330,
                distance_leg: 84,
                distance_accumulated: 162,
                distance_remaining: 331,
                position_ident_1: "GUSKO",
                position_ident_2: "GUSKO",
                position_type: "A",
                position_frequency: nil,
                time_leg: 13,
                time_accumulated: 27,
                time_remaining: 55,
                eto: DateTimeFunctions.stringToDate("2022-06-14 06:55:21") ?? nil,
                reto: DateTimeFunctions.stringToDate("2022-06-14 06:55:21") ?? nil,
                ato: DateTimeFunctions.stringToDate("2022-06-14 06:28:21") ?? nil,
                fl: 380,
                climb_descent: nil,
                mora: 75,
                tas: 378,
                gs: 377,
                wv_w: 60,
                wv_v: 25,
                wv_wc_dir: "H",
                wv_wc_qty: 1,
                wv_cat: 0,
                sat: -61,
                isa_data: 0,
                temperature: -56,
                fuel_flow: 1593,
                fuel_flow_eng: 796,
                fuel_leg: 0,
                fuel_used_accumulated: 1446,
                fuel_rem: 2772,
                fuel_rem_ind: 2773,
                fuel_rem_calc: 2637,
                fuel_req_min: 1233,
                lat: -3.91890001,
                lon: 105.23829651,
                remarks: "",
                meta: "[]",
                landing_time: DateTimeFunctions.stringToDate("1970-01-01 00:00:00") ?? nil,
                engine_off_time: DateTimeFunctions.stringToDate("1970-01-01 00:00:00") ?? nil,
                engine_on_time: DateTimeFunctions.stringToDate("1970-01-01 00:00:00") ?? nil,
                pax: nil,
                pax_weight: nil,
                cargo_weight: nil,
                landing_fuel: nil,
                uplift_fuel: nil
            ),
        
            FlightWaypointsDB(
                id: 197,
                flight_id: 500000,
                wp_id: 5004,
                status: 1,
                route: 16,
                type: 0,
                fir_1: "WI",
                fir_2: "WIIF",
                airway: "A585",
                variation: 0,
                magnetic_track: 331,
                true_track: 331,
                distance_leg: 71,
                distance_accumulated: 233,
                distance_remaining: 260,
                position_ident_1: "PLB",
                position_ident_2: "PALEMBANG",
                position_type: "D",
                position_frequency: 115.5,
                time_leg: 11,
                time_accumulated: 38,
                time_remaining: 44,
                eto: DateTimeFunctions.stringToDate("2022-06-14 07:06:21") ?? nil,
                reto: DateTimeFunctions.stringToDate("2022-06-14 07:06:21") ?? nil,
                ato: DateTimeFunctions.stringToDate("2022-06-14 06:28:21") ?? nil,
                fl: 380,
                climb_descent: nil,
                mora: 16,
                tas: 376,
                gs: 376,
                wv_w: 63,
                wv_v: 24,
                wv_wc_dir: "H",
                wv_wc_qty: 0,
                wv_cat: 0,
                sat: -61,
                isa_data: 0,
                temperature: -56,
                fuel_flow: 1582,
                fuel_flow_eng: 791,
                fuel_leg: 0,
                fuel_used_accumulated: 1745,
                fuel_rem: 2473,
                fuel_rem_ind: 2474,
                fuel_rem_calc: 2338,
                fuel_req_min: 123,
                lat: -2.87859988,
                lon: 104.65319824,
                remarks: "",
                meta: "[]",
                landing_time: DateTimeFunctions.stringToDate("1970-01-01 00:00:00") ?? nil,
                engine_off_time: DateTimeFunctions.stringToDate("1970-01-01 00:00:00") ?? nil,
                engine_on_time: DateTimeFunctions.stringToDate("1970-01-01 00:00:00") ?? nil,
                pax: nil,
                pax_weight: nil,
                cargo_weight: nil,
                landing_fuel: nil,
                uplift_fuel: nil
            ),
        
            FlightWaypointsDB(
                id: 198,
                flight_id: 500000,
                wp_id: 6005,
                status: 1,
                route: 16,
                type: 0,
                fir_1: "WI",
                fir_2: "WIIF",
                airway: "G579",
                variation: 0,
                magnetic_track: 349,
                true_track: 349,
                distance_leg: 141,
                distance_accumulated: 374,
                distance_remaining: 119,
                position_ident_1: "PARDI",
                position_ident_2: "PARDI",
                position_type: "A",
                position_frequency: nil,
                time_leg: 23,
                time_accumulated: 61,
                time_remaining: 21,
                eto: DateTimeFunctions.stringToDate("2022-06-14 07:29:21") ?? nil,
                reto: DateTimeFunctions.stringToDate("2022-06-14 07:29:21") ?? nil,
                ato: DateTimeFunctions.stringToDate("2022-06-14 06:28:21") ?? nil,
                fl: 380,
                climb_descent: nil,
                mora: 46,
                tas: 375,
                gs: 369,
                wv_w: 67,
                wv_v: 26,
                wv_wc_dir: "H",
                wv_wc_qty: 6,
                wv_cat: 0,
                sat: -61,
                isa_data: 0,
                temperature: -56,
                fuel_flow: 1561,
                fuel_flow_eng: 780,
                fuel_leg: 0,
                fuel_used_accumulated: 2341,
                fuel_rem: 1877,
                fuel_rem_ind: 1878,
                fuel_rem_calc: 1742,
                fuel_req_min: 12432,
                lat: -0.56669998,
                lon: 104.21669769,
                remarks: "",
                meta: "[]",
                landing_time: DateTimeFunctions.stringToDate("1970-01-01 00:00:00") ?? nil,
                engine_off_time: DateTimeFunctions.stringToDate("1970-01-01 00:00:00") ?? nil,
                engine_on_time: DateTimeFunctions.stringToDate("1970-01-01 00:00:00") ?? nil,
                pax: nil,
                pax_weight: nil,
                cargo_weight: nil,
                landing_fuel: nil,
                uplift_fuel: nil
            ),
        
        FlightWaypointsDB(
               id: 199,
               flight_id: 500000,
               wp_id: 7006,
               status: 1,
               route: 16,
               type: 0,
               fir_1: "",
               fir_2: "",
               airway: "",
               variation: 0,
               magnetic_track: 348,
               true_track: 348,
               distance_leg: 17,
               distance_accumulated: 391,
               distance_remaining: 102,
               position_ident_1: "-TOD-",
               position_ident_2: "",
               position_type: "",
               position_frequency: nil,
               time_leg: 3,
               time_accumulated: 64,
               time_remaining: 18,
               eto: DateTimeFunctions.stringToDate("2022-06-14 07:32:21") ?? nil,
               reto: DateTimeFunctions.stringToDate("2022-06-14 07:32:21") ?? nil,
               ato: DateTimeFunctions.stringToDate("2022-06-14 06:28:21") ?? nil,
               fl: 380,
               climb_descent: nil,
               mora: 46,
               tas: 375,
               gs: 369,
               wv_w: 67,
               wv_v: 26,
               wv_wc_dir: "H",
               wv_wc_qty: 6,
               wv_cat: 0,
               sat: -61,
               isa_data: 0,
               temperature: -56,
               fuel_flow: 1561,
               fuel_flow_eng: 780,
               fuel_leg: 0,
               fuel_used_accumulated: 2413,
               fuel_rem: 1805,
               fuel_rem_ind: nil,
               fuel_rem_calc: 1670,
               fuel_req_min: 1231532,
               lat: -0.28920001,
               lon: 104.15930176,
               remarks: "",
               meta: "[]",
               landing_time: DateTimeFunctions.stringToDate("1970-01-01 00:00:00") ?? nil,
               engine_off_time: DateTimeFunctions.stringToDate("1970-01-01 00:00:00") ?? nil,
               engine_on_time: DateTimeFunctions.stringToDate("1970-01-01 00:00:00") ?? nil,
               pax: nil,
               pax_weight: nil,
               cargo_weight: nil,
               landing_fuel: nil,
               uplift_fuel: nil
           ),
           FlightWaypointsDB(
               id: 200,
               flight_id: 500000,
               wp_id: 8007,
               status: 1,
               route: 16,
               type: 0,
               fir_1: "WS",
               fir_2: "WSJC",
               airway: "G579",
               variation: 0,
               magnetic_track: 348,
               true_track: 348,
               distance_leg: 2,
               distance_accumulated: 393,
               distance_remaining: 100,
               position_ident_1: "FIRJ3",
               position_ident_2: "FIR WSJC/WIIF F",
               position_type: "A",
               position_frequency: nil,
               time_leg: 0,
               time_accumulated: 64,
               time_remaining: 18,
               eto: DateTimeFunctions.stringToDate("2022-06-14 07:32:21") ?? nil,
               reto: DateTimeFunctions.stringToDate("2022-06-14 07:32:21") ?? nil,
               ato: DateTimeFunctions.stringToDate("2022-06-14 06:28:21") ?? nil,
               fl: 380,
               climb_descent: nil,
               mora: 46,
               tas: 372,
               gs: 366,
               wv_w: 69,
               wv_v: 29,
               wv_wc_dir: "H",
               wv_wc_qty: 6,
               wv_cat: 0,
               sat: -61,
               isa_data: 0,
               temperature: -56,
               fuel_flow: 1561,
               fuel_flow_eng: 780,
               fuel_leg: 0,
               fuel_used_accumulated: 2419,
               fuel_rem: 1799,
               fuel_rem_ind: 1800,
               fuel_rem_calc: 1664,
               fuel_req_min: 123421,
               lat: -0.26830000,
               lon: 104.15499878,
               remarks: "",
               meta: "[]",
               landing_time: DateTimeFunctions.stringToDate("1970-01-01 00:00:00") ?? nil,
               engine_off_time: DateTimeFunctions.stringToDate("1970-01-01 00:00:00") ?? nil,
               engine_on_time: DateTimeFunctions.stringToDate("1970-01-01 00:00:00") ?? nil,
               pax: nil,
               pax_weight: nil,
               cargo_weight: nil,
               landing_fuel: nil,
               uplift_fuel: nil
           ),
           FlightWaypointsDB(
               id: 201,
               flight_id: 500000,
               wp_id: 9008,
               status: 1,
               route: 16,
               type: 0,
               fir_1: "WS",
               fir_2: "WSJC",
               airway: "G579",
               variation: 0,
               magnetic_track: 349,
               true_track: 349,
               distance_leg: 33,
               distance_accumulated: 426,
               distance_remaining: 67,
               position_ident_1: "REPOV",
               position_ident_2: "REPOV",
               position_type: "A",
               position_frequency: nil,
               time_leg: 6,
               time_accumulated: 70,
               time_remaining: 12,
               eto: DateTimeFunctions.stringToDate("2022-06-14 07:38:21") ?? nil,
               reto: DateTimeFunctions.stringToDate("2022-06-14 07:38:21") ?? nil,
               ato: DateTimeFunctions.stringToDate("2022-06-14 06:28:21") ?? nil,
               fl: 380,
               climb_descent: nil,
               mora: 46,
               tas: 337,
               gs: 331,
               wv_w: 69,
               wv_v: 29,
               wv_wc_dir: "H",
               wv_wc_qty: 6,
               wv_cat: 0,
               sat: -61,
               isa_data: 0,
               temperature: -56,
               fuel_flow: 1561,
               fuel_flow_eng: 780,
               fuel_leg: 0,
               fuel_used_accumulated: 2515,
               fuel_rem: 1703,
               fuel_rem_ind: 1704,
               fuel_rem_calc: 1568,
               fuel_req_min: 123412,
               lat: 0.27309999,
               lon: 104.05000305,
               remarks: "",
               meta: "[]",
               landing_time: DateTimeFunctions.stringToDate("1970-01-01 00:00:00") ?? nil,
               engine_off_time: DateTimeFunctions.stringToDate("1970-01-01 00:00:00") ?? nil,
               engine_on_time: DateTimeFunctions.stringToDate("1970-01-01 00:00:00") ?? nil,
               pax: nil,
               pax_weight: nil,
               cargo_weight: nil,
               landing_fuel: nil,
               uplift_fuel: nil
           ),
           FlightWaypointsDB(
               id: 202,
               flight_id: 500000,
               wp_id: 10009,
               status: 4,
               route: 16,
               type: 2,
               fir_1: "",
               fir_2: "",
               airway: "",
               variation: 0,
               magnetic_track: 357,
               true_track: 357,
               distance_leg: 67,
               distance_accumulated: 493,
               distance_remaining: 0,
               position_ident_1: "WSSS",
               position_ident_2: "",
               position_type: "",
               position_frequency: nil,
               time_leg: 12,
               time_accumulated: 82,
               time_remaining: 0,
               eto: DateTimeFunctions.stringToDate("2022-06-14 07:50:21") ?? nil,
               reto: DateTimeFunctions.stringToDate("2022-06-14 07:50:21") ?? nil,
               ato: nil,
               fl: 0,
               climb_descent: nil,
               mora: 34,
               tas: 337,
               gs: 331,
               wv_w: 69,
               wv_v: 29,
               wv_wc_dir: "H",
               wv_wc_qty: 6,
               wv_cat: 0,
               sat: 0,
               isa_data: 0,
               temperature: 15,
               fuel_flow: 1561,
               fuel_flow_eng: 780,
               fuel_leg: 0,
               fuel_used_accumulated: 2709,
               fuel_rem: 1509,
               fuel_rem_ind: 1510,
               fuel_rem_calc: 1374,
               fuel_req_min: 12341234,
               lat: 1.35920000,
               lon: 103.98930359,
               remarks: "",
               meta: "[]",
               landing_time: DateTimeFunctions.stringToDate("1970-01-01 00:00:00") ?? nil,
               engine_off_time: DateTimeFunctions.stringToDate("1970-01-01 00:00:00") ?? nil,
               engine_on_time: DateTimeFunctions.stringToDate("1970-01-01 00:00:00") ?? nil,
               pax: nil,
               pax_weight: nil,
               cargo_weight: nil,
               landing_fuel: nil,
               uplift_fuel: nil
           ),
           FlightWaypointsDB(
               id: 203,
               flight_id: 500000,
               wp_id: 11000,
               status: 0,
               route: 32,
               type: 0,
               fir_1: "",
               fir_2: "",
               airway: "",
               variation: 0,
               magnetic_track: 294,
               true_track: 294,
               distance_leg: 18,
               distance_accumulated: 511,
               distance_remaining: 15,
               position_ident_1: "SEL",
               position_ident_2: "",
               position_type: "",
               position_frequency: 220,
               time_leg: 4,
               time_accumulated: 86,
               time_remaining: 4,
               eto: DateTimeFunctions.stringToDate("2022-06-14 07:54:21") ?? nil,
               reto: DateTimeFunctions.stringToDate("2022-06-14 07:54:21") ?? nil,
               ato: nil,
               fl: 40,
               climb_descent: nil,
               mora: 34,
               tas: 231,
               gs: 251,
               wv_w: 69,
               wv_v: 29,
               wv_wc_dir: "T",
               wv_wc_qty: 20,
               wv_cat: 0,
               sat: 7,
               isa_data: 0,
               temperature: 7,
               fuel_flow: 2196,
               fuel_flow_eng: 0,
               fuel_leg: 0,
               fuel_used_accumulated: 2914,
               fuel_rem: 1304,
               fuel_rem_ind: 1305,
               fuel_rem_calc: 1169,
               fuel_req_min: 123124,
               lat: 1.41349995,
               lon: 103.86949921,
               remarks: "",
               meta: "[]",
               landing_time: DateTimeFunctions.stringToDate("1970-01-01 00:00:00") ?? nil,
               engine_off_time: DateTimeFunctions.stringToDate("1970-01-01 00:00:00") ?? nil,
               engine_on_time: DateTimeFunctions.stringToDate("1970-01-01 00:00:00") ?? nil,
               pax: nil,
               pax_weight: nil,
               cargo_weight: nil,
               landing_fuel: nil,
               uplift_fuel: nil
           ),
           FlightWaypointsDB(
               id: 204,
               flight_id: 500000,
               wp_id: 12001,
               status: 0,
               route: 32,
               type: 2,
               fir_1: "",
               fir_2: "",
               airway: "",
               variation: 0,
               magnetic_track: 332,
               true_track: 332,
               distance_leg: 15,
               distance_accumulated: 526,
               distance_remaining: 0,
               position_ident_1: "WSSL",
               position_ident_2: "",
               position_type: "",
               position_frequency: nil,
               time_leg: 4,
               time_accumulated: 90,
               time_remaining: 0,
               eto: DateTimeFunctions.stringToDate("2022-06-14 07:58:21") ?? nil,
               reto: DateTimeFunctions.stringToDate("2022-06-14 07:58:21") ?? nil,
               ato: nil,
               fl: 0,
               climb_descent: nil,
               mora: 34,
               tas: 231,
               gs: 233,
               wv_w: 69,
               wv_v: 29,
               wv_wc_dir: "T",
               wv_wc_qty: 2,
               wv_cat: 0,
               sat: 0,
               isa_data: 0,
               temperature: 15,
               fuel_flow: 2192,
               fuel_flow_eng: 0,
               fuel_leg: 0,
               fuel_used_accumulated: 2999,
               fuel_rem: 1219,
               fuel_rem_ind: 1220,
               fuel_rem_calc: 1084,
               fuel_req_min: 12345,
               lat: 1.41700006,
               lon: 103.86759949,
               remarks: "",
               meta: "[]",
               landing_time: DateTimeFunctions.stringToDate("1970-01-01 00:00:00") ?? nil,
               engine_off_time: DateTimeFunctions.stringToDate("1970-01-01 00:00:00") ?? nil,
               engine_on_time: DateTimeFunctions.stringToDate("1970-01-01 00:00:00") ?? nil,
               pax: nil,
               pax_weight: nil,
               cargo_weight: nil,
               landing_fuel: nil,
               uplift_fuel: nil
           ),
           FlightWaypointsDB(
               id: 205,
               flight_id: 500001,
               wp_id: 1000,
               status: 1,
               route: 16,
               type: 1,
               fir_1: "",
               fir_2: "",
               airway: "",
               variation: -1,
               magnetic_track: 0,
               true_track: 0,
               distance_leg: 0,
               distance_accumulated: 0,
               distance_remaining: 655,
               position_ident_1: "VTBS",
               position_ident_2: "",
               position_type: "",
               position_frequency: nil,
               time_leg: 0,
               time_accumulated: 0,
               time_remaining: 122,
               eto: DateTimeFunctions.stringToDate("2022-09-02 05:57:08") ?? nil,
               reto: DateTimeFunctions.stringToDate("2022-09-02 05:57:08") ?? nil,
               ato: DateTimeFunctions.stringToDate("2022-09-02 05:57:08") ?? nil,
               fl: 270,
               climb_descent: nil,
               mora: 0,
               tas: 0,
               gs: 0,
               wv_w: 0,
               wv_v: 0,
               wv_wc_dir: "H",
               wv_wc_qty: 0,
               wv_cat: 0,
               sat: -39,
               isa_data: 0,
               temperature: -39,
               fuel_flow: 0,
               fuel_flow_eng: 0,
               fuel_leg: 0,
               fuel_used_accumulated: 11453,
               fuel_rem: 11453,
               fuel_rem_ind: 11233,
               fuel_rem_calc: 0,
               fuel_req_min: 1234124,
               lat: 13.68579960,
               lon: 100.74890137,
               remarks: "",
               meta: "[]",
               landing_time: DateTimeFunctions.stringToDate("1970-01-01 00:00:00") ?? nil,
               engine_off_time: DateTimeFunctions.stringToDate("1970-01-01 00:00:00") ?? nil,
               engine_on_time: DateTimeFunctions.stringToDate("1970-01-01 00:00:00") ?? nil,
               pax: nil,
               pax_weight: nil,
               cargo_weight: nil,
               landing_fuel: nil,
               uplift_fuel: nil
           )
    ]
}
