//
//  FlightDataDbMockData.swift
//  taillog
//
//  Created by Shubham Tiwari on 31/07/24.
//

import Foundation

class FlightDataDbMockData{
   static let mockData = [
        FlightDataDB(
            id: 400029,
            flight_id: 500038,
            route: 32,
            user_remarks: nil,
            icfa_remarks: nil,
            technical_log_no: nil,
            sign_date: nil,
            pic_sign_date: nil,
            sign_by_pin: false, // Boolean represented as 0 in MySQL
            security_search_check: nil,
            check_cat_2: nil,
            successfull_cat_2: nil,
            unsuccessfull_cat_2: nil,
            flight_plan_id: "12250",
            dispatcher: nil,
            gufi: nil,
            aircraft_config: nil,
            operations_type: "{\"op1\":\"Scheduled\",\"op3\":\"IFR\"}",
            pic_flying: nil,
            pic_to: nil,
            day_to: nil,
            pic_instrument_approach: nil,
            instrument_approach_info: nil,
            pic_ld: nil,
            day_ld: nil,
            landing_dist_reqd: nil,
            landing_dist_avail: nil,
            dispatch_msg: nil,
            fms_ident: nil,
            dep_cat: nil,
            dest_cat: nil,
            alt1_cat: "250/287/M78 ",
            alt2_cat: "CI025",
            era_cat: "M78/291/250 ",
            toalt_cat: nil,
            hora_departure: nil,
            hora_arrival: nil,
            alt2AsInfoOnly: false, // Boolean represented as 0 in MySQL
            atc_ctot: "FAOR RWY-03L DCT RAGUL UQ10 CSV UZ26 ERDAS DCT RWY-01 FACT FAOR/FL380",
            ctot_updated_at: nil,
            times_ctot: DateTimeFunctions.stringToDate("2024-06-11 07:30:00") ?? nil,
            eta: DateTimeFunctions.stringToDate("2024-06-11 09:50:00") ?? nil,
            delay_codes: nil,
            times_off: DateTimeFunctions.stringToDate("2024-06-11 07:40:00") ?? nil,
            times_on: DateTimeFunctions.stringToDate("2024-06-11 09:40:00") ?? nil,
            times_blk: nil,
            times_airb: nil,
            times_land: nil,
            times_flt: nil,
            landing_cycles: nil,
            aircraft_cycles_pre_flight: nil,
            ttsn: nil,
            atc_route: "FAOR RWY-03L DCT RAGUL UQ10 CSV UZ26 ERDAS DCT RWY-01 FACT FAOR/FL380",
            atc_status: nil,
            route_fir_trans: nil,
            route_climb: nil,
            route_cruise: nil,
            route_descend: nil,
            route_hold: nil,
            aircraft_cruise_profiles: nil,
            route_distance: 845,
            route_gcd: 686,
            route_ratio: 1.231778425656,
            route_fl: 380,
            route_fl_min: 380,
            route_fl_max: 380,
            route_tt_avg: nil,
            route_wv_vcomp: -86,
            enroute_text: nil,
            temp_toc: -55,
            to_airport: "FAOR",
            to_settings: "[]",
            ld_airport: "FACT",
            engine_time: nil,
            ld_settings: "[]",
            oil_uplift_left: nil,
            oil_uplift_center: nil,
            oil_uplift_right: nil,
            oil_uplift_apu: nil,
            prist_litres_uplift: nil,
            fuel_trip: 10622,
            fuel_trip_time: 7200,
            fuel_taxi: 400,
            fuel_taxi_time: 600,
            fuel_cont: 531,
            fuel_cont_time: 360,
            fuel_cont_pct: nil,
            fuel_alt1: 3104,
            fuel_alt1_time: 1800,
            fuel_alt2: nil,
            fuel_alt2_time: nil,
            fuel_hold: 2204,
            fuel_hold_time: 1800,
            fuel_comp: 39,
            fuel_comp_time: 0,
            fuel_ramp_min: nil,
            fuel_additional: nil,
            fuel_holding: nil,
            fuel_holding_time: nil,
            fuel_comp_extra: nil,
            fuel_comp_extra_time: nil,
            fuel_additional_time: nil,
            fuel_extra: nil,
            fuel_extra_time: nil,
            fuel_ramp: nil,
            fuel_ramp_time: nil,
            fuel_extra_corrected: nil,
            fuel_discretionary: nil,
            fuel_required: 96521,
            fuel_dest_min: 0,
            fuel_ld: 96521,
            touchdown_weight: 134481,
            fuel_gain_loss: "",
            fuel_correction: nil,
            fuel_last_flight: 113021,
            fuel_burned_before_uplift: 152820,
            fuel_before_uplift: nil,
            fuel_uplift: 102399,
            fuel_ramp_actual: 142198,
            fuel_burned_after_uplift: nil,
            fuel_engine_on: nil,
            fuel_take_off: nil,
            fuel_burned_engine: nil,
            fuel_on_block: nil,
            fuel_burned_after_engineoff: nil,
            fuel_after_flight: nil,
            fuel_burned_total: nil,
            fuel_trip_actual: nil,
            fuel_ramp_max: nil,
            fuel_type: nil,
            fuel_density: 0.8040,
            remark_extra_fuel_consumption: nil,
            reason_extra_fuel: nil,
            reason_additional_fuel: nil,
            reason_tech_log_change: nil,
            pax: 0,
            pax_male: 0,
            pax_female: 0,
            pax_child: 0,
            pax_infant: 0,
            dest2: nil,
            dest3: nil,
            pax_qty_dest1: nil,
            pax_qty_dest2: nil,
            pax_qty_dest3: nil,
            weight_pax: 96521,
            weight_cargo: 0,
            weight_bo: 96521,
            weight_payload: 134481,
            weight_zf: nil,
            weight_zf_max: nil,
            weight_ramp: 113021,
            weight_ramp_max: 152820,
            weight_to: nil,
            weight_to_max: 102399,
            weight_to_max_regulated: 142198,
            weight_ld: nil,
            weight_ld_max: nil,
            weight_ld_max_regulated: nil,
            fir_list: "[]",
            adequate_airport_list: "[\"FAOR\",\"FACT\"]",
            alternate_airport_list: "[]",
            weather_updated_at: DateTimeFunctions.stringToDate("0000-00-00 00:00:00") ?? Date(),
            documents_updated_at: nil,
            sid_procedure: nil,
            star_procedure: nil,
            app_config: nil,
            change_log: nil,
            created_at: DateTimeFunctions.stringToDate("2024-06-11 06:06:40") ?? Date(),
            updated_at: DateTimeFunctions.stringToDate("2024-06-11 06:06:40") ?? Date()
        ),
        
        FlightDataDB(
            id: 400030,
            flight_id: 500039,
            route: 32,
            user_remarks: nil,
            icfa_remarks: nil,
            technical_log_no: nil,
            sign_date: nil,
            pic_sign_date: nil,
            sign_by_pin: false, // Boolean represented as 0 in MySQL
            security_search_check: nil,
            check_cat_2: nil,
            successfull_cat_2: nil,
            unsuccessfull_cat_2: nil,
            flight_plan_id: "12261",
            dispatcher: nil,
            gufi: nil,
            aircraft_config: nil,
            operations_type: "{\"op1\":\"Scheduled\",\"op3\":\"IFR\"}",
            pic_flying: nil,
            pic_to: nil,
            day_to: nil,
            pic_instrument_approach: nil,
            instrument_approach_info: nil,
            pic_ld: nil,
            day_ld: nil,
            landing_dist_reqd: nil,
            landing_dist_avail: nil,
            dispatch_msg: nil,
            fms_ident: nil,
            dep_cat: "250/287/M78 ",
            dest_cat: "CI025",
            alt1_cat: "M78/291/250 ",
            alt2_cat: nil,
            era_cat: nil,
            toalt_cat: nil,
            hora_departure:  nil,
            hora_arrival: nil,
            alt2AsInfoOnly: false, // Boolean represented as 0 in MySQL
            atc_ctot: "FACT RWY-19 TETAN1A TETAN UZ2 NIBEX NIBEX2A RWY-03R FAOR FACT/FL390",
            ctot_updated_at: nil,
            times_ctot: DateTimeFunctions.stringToDate("2024-06-11 11:10:00") ?? nil,
            eta: DateTimeFunctions.stringToDate("2024-06-11 12:39:00") ?? nil,
            delay_codes: nil,
            times_off: DateTimeFunctions.stringToDate("2024-06-11 11:10:00") ?? nil,
            times_on: DateTimeFunctions.stringToDate("2024-06-11 12:39:00") ?? nil,
            times_blk: nil,
            times_airb: nil,
            times_land: nil,
            times_flt: nil,
            landing_cycles: nil,
            aircraft_cycles_pre_flight: nil,
            ttsn: nil,
            atc_route: "FACT RWY-19 TETAN1A TETAN UZ2 NIBEX NIBEX2A RWY-03R FAOR FACT/FL390",
            atc_status: nil,
            route_fir_trans: nil,
            route_climb: nil,
            route_cruise: nil,
            route_descend: nil,
            route_hold: nil,
            aircraft_cruise_profiles: nil,
            route_distance: 616,
            route_gcd: 686,
            route_ratio: 0.897959183673,
            route_fl: 390,
            route_fl_min: 390,
            route_fl_max: 390,
            route_tt_avg: nil,
            route_wv_vcomp: 79,
            enroute_text: nil,
            temp_toc: -57,
            to_airport: "FACT",
            to_settings: "[]",
            ld_airport: "FAOR",
            engine_time: nil,
            ld_settings: "[]",
            oil_uplift_left: nil,
            oil_uplift_center: nil,
            oil_uplift_right: nil,
            oil_uplift_apu: nil,
            prist_litres_uplift: nil,
            fuel_trip: 7907,
            fuel_trip_time: 5340,
            fuel_taxi: 400,
            fuel_taxi_time: 600,
            fuel_cont: 395,
            fuel_cont_time: 300,
            fuel_cont_pct: nil,
            fuel_alt1: 2340,
            fuel_alt1_time: 1320,
            fuel_alt2: nil,
            fuel_alt2_time: nil,
            fuel_hold: 2106,
            fuel_hold_time: 1800,
            fuel_comp: 52,
            fuel_comp_time: 60,
            fuel_ramp_min: nil,
            fuel_additional: nil,
            fuel_holding: nil,
            fuel_holding_time: nil,
            fuel_comp_extra: nil,
            fuel_comp_extra_time: nil,
            fuel_additional_time: nil,
            fuel_extra: nil,
            fuel_extra_time: nil,
            fuel_ramp: nil,
            fuel_ramp_time: nil,
            fuel_extra_corrected: nil,
            fuel_discretionary: nil,
            fuel_required: 96521,
            fuel_dest_min: 0,
            fuel_ld: 96521,
            touchdown_weight: 134481,
            fuel_gain_loss: "",
            fuel_correction: nil,
            fuel_last_flight: 109321,
            fuel_burned_before_uplift: 150105,
            fuel_before_uplift: nil,
            fuel_uplift: 101414,
            fuel_ramp_actual: 142198,
            fuel_burned_after_uplift: nil,
            fuel_engine_on: nil,
            fuel_take_off: nil,
            fuel_burned_engine: nil,
            fuel_on_block: nil,
            fuel_burned_after_engineoff: nil,
            fuel_after_flight: nil,
            fuel_burned_total: nil,
            fuel_trip_actual: nil,
            fuel_ramp_max: nil,
            fuel_type: nil,
            fuel_density: 0.8040,
            remark_extra_fuel_consumption: nil,
            reason_extra_fuel: nil,
            reason_additional_fuel: nil,
            reason_tech_log_change: nil,
            pax: 0,
            pax_male: 0,
            pax_female: 0,
            pax_child: 0,
            pax_infant: 0,
            dest2: nil,
            dest3: nil,
            pax_qty_dest1: nil,
            pax_qty_dest2: nil,
            pax_qty_dest3: nil,
            weight_pax: 96521,
            weight_cargo: 0,
            weight_bo: 96521,
            weight_payload: 134481,
            weight_zf: nil,
            weight_zf_max: nil,
            weight_ramp: 113021,
            weight_ramp_max: 152820,
            weight_to: nil,
            weight_to_max: 102399,
            weight_to_max_regulated: 142198,
            weight_ld: nil,
            weight_ld_max: nil,
            weight_ld_max_regulated: nil,
            fir_list: "[]",
            adequate_airport_list: "[\"FACT\",\"FAOR\"]",
            alternate_airport_list: "[]",
            weather_updated_at: DateTimeFunctions.stringToDate("0000-00-00 00:00:00") ?? Date(),
            documents_updated_at: nil,
            sid_procedure: "TETA1A",
            star_procedure: "NIBE2A",
            app_config: nil,
            change_log: nil,
            created_at: DateTimeFunctions.stringToDate("2024-06-11 06:06:50") ?? nil,
            updated_at: DateTimeFunctions.stringToDate("2024-06-11 06:06:50") ?? nil
        ),
        
        FlightDataDB(
            id: 400031,
            flight_id: 500040,
            route: 32,
            user_remarks: nil,
            icfa_remarks: nil,
            technical_log_no: nil,
            sign_date: nil,
            pic_sign_date: nil,
            sign_by_pin: false, // Boolean represented as 0 in MySQL
            security_search_check: nil,
            check_cat_2: nil,
            successfull_cat_2: nil,
            unsuccessfull_cat_2: nil,
            flight_plan_id: "12271",
            dispatcher: nil,
            gufi: nil,
            aircraft_config: nil,
            operations_type: "{\"op1\":\"Scheduled\",\"op3\":\"IFR\"}",
            pic_flying: nil,
            pic_to: nil,
            day_to: nil,
            pic_instrument_approach: nil,
            instrument_approach_info: nil,
            pic_ld: nil,
            day_ld: nil,
            landing_dist_reqd: nil,
            landing_dist_avail: nil,
            dispatch_msg: nil,
            fms_ident: "FPL-GBB133J-IS -A320/M-SDGHIRWY/S -FAOR1400 -N0457F380 DCT RAGUL UQ10 CSV UZ26 ERDAS DCT -FACT0200 FAGG -PBN/A1B1L1O1S1S2 DOF/240611 REG/ZSGAO EET/FACA0108 OPR/GLOBAL AVIATION 0027825689347 RMK/SARNML",
            dep_cat: "250/287/M78 ",
            dest_cat: "CI025",
            alt1_cat: "M78/291/250 ",
            alt2_cat: nil,
            era_cat: nil,
            toalt_cat: nil,
            hora_departure: nil,
            hora_arrival: nil,
            alt2AsInfoOnly: false, // Boolean represented as 0 in MySQL
            atc_ctot: "FAOR RWY-03L DCT RAGUL UQ10 CSV UZ26 ERDAS DCT RWY-01 FACT FAOR/FL380",
            ctot_updated_at: nil,
            times_ctot: DateTimeFunctions.stringToDate("2024-06-11 14:10:00"),
            eta: DateTimeFunctions.stringToDate("2024-06-11 16:10:00"),
            delay_codes: nil,
            times_off: DateTimeFunctions.stringToDate("2024-06-11 14:10:00"),
            times_on: DateTimeFunctions.stringToDate("2024-06-11 16:10:00"),
            times_blk: nil,
            times_airb: nil,
            times_land: nil,
            times_flt: nil,
            landing_cycles: nil,
            aircraft_cycles_pre_flight: nil,
            ttsn: nil,
            atc_route: "FAOR RWY-03L DCT RAGUL UQ10 CSV UZ26 ERDAS DCT RWY-01 FACT FAOR/FL380",
            atc_status: nil,
            route_fir_trans: nil,
            route_climb: nil,
            route_cruise: nil,
            route_descend: nil,
            route_hold: nil,
            aircraft_cruise_profiles: nil,
            route_distance: 837,
            route_gcd: 686,
            route_ratio: 1.220116618076,
            route_fl: 380,
            route_fl_min: 380,
            route_fl_max: 380,
            route_tt_avg: nil,
            route_wv_vcomp: -82,
            enroute_text: nil,
            temp_toc: -54,
            to_airport: "FAOR",
            to_settings: "[]",
            ld_airport: "FACT",
            engine_time: nil,
            ld_settings: "[]",
            oil_uplift_left: nil,
            oil_uplift_center: nil,
            oil_uplift_right: nil,
            oil_uplift_apu: nil,
            prist_litres_uplift: nil,
            fuel_trip: 10584,
            fuel_trip_time: 7200,
            fuel_taxi: 400,
            fuel_taxi_time: 600,
            fuel_cont: 529,
            fuel_cont_time: 360,
            fuel_cont_pct: nil,
            fuel_alt1: 3055,
            fuel_alt1_time: 1860,
            fuel_alt2: nil,
            fuel_alt2_time: nil,
            fuel_hold: 2209,
            fuel_hold_time: 1800,
            fuel_comp: 23,
            fuel_comp_time: 0,
            fuel_ramp_min: nil,
            fuel_additional: nil,
            fuel_holding: nil,
            fuel_holding_time: nil,
            fuel_comp_extra: nil,
            fuel_comp_extra_time: nil,
            fuel_additional_time: nil,
            fuel_extra: nil,
            fuel_extra_time: nil,
            fuel_ramp: nil,
            fuel_ramp_time: nil,
            fuel_extra_corrected: nil,
            fuel_discretionary: nil,
            fuel_required: 96521,
            fuel_dest_min: 0,
            fuel_ld: 96521,
            touchdown_weight: 134481,
            fuel_gain_loss: "",
            fuel_correction: nil,
            fuel_last_flight: 112921,
            fuel_burned_before_uplift: 152782,
            fuel_before_uplift: nil,
            fuel_uplift: 102337,
            fuel_ramp_actual: 142198,
            fuel_burned_after_uplift: nil,
            fuel_engine_on: nil,
            fuel_take_off: nil,
            fuel_burned_engine: nil,
            fuel_on_block: nil,
            fuel_burned_after_engineoff: nil,
            fuel_after_flight: nil,
            fuel_burned_total: nil,
            fuel_trip_actual: nil,
            fuel_ramp_max: nil,
            fuel_type: nil,
            fuel_density: 0.8040,
            remark_extra_fuel_consumption: nil,
            reason_extra_fuel: nil,
            reason_additional_fuel: nil,
            reason_tech_log_change: nil,
            pax: 0,
            pax_male: 0,
            pax_female: 0,
            pax_child: 0,
            pax_infant: 0,
            dest2: nil,
            dest3: nil,
            pax_qty_dest1: nil,
            pax_qty_dest2: nil,
            pax_qty_dest3: nil,
            weight_pax: 96521,
            weight_cargo: 0,
            weight_bo: 96521,
            weight_payload: 134481,
            weight_zf: nil,
            weight_zf_max: nil,
            weight_ramp: 112921,
            weight_ramp_max: 152782,
            weight_to: nil,
            weight_to_max: 102337,
            weight_to_max_regulated: 142198,
            weight_ld: nil,
            weight_ld_max: nil,
            weight_ld_max_regulated: nil,
            fir_list: "[]",
            adequate_airport_list: "[\"FAOR\",\"FACT\"]",
            alternate_airport_list: "[]",
            weather_updated_at: DateTimeFunctions.stringToDate("0000-00-00 00:00:00") ?? Date(),
            documents_updated_at: nil,
            sid_procedure: nil,
            star_procedure: nil,
            app_config: nil,
            change_log: nil,
            created_at: DateTimeFunctions.stringToDate("2024-06-11 06:07:00"),
            updated_at: DateTimeFunctions.stringToDate("2024-06-11 06:07:01")
        ),
        
        FlightDataDB(
            id: 400032,
            flight_id: 500041,
            route: 32,
            user_remarks: nil,
            icfa_remarks: nil,
            technical_log_no: nil,
            sign_date: nil,
            pic_sign_date: nil,
            sign_by_pin: false, // Boolean represented as 0 in MySQL
            security_search_check: nil,
            check_cat_2: nil,
            successfull_cat_2: nil,
            unsuccessfull_cat_2: nil,
            flight_plan_id: "12278",
            dispatcher: nil,
            gufi: nil,
            aircraft_config: nil,
            operations_type: "{\"op1\":\"Scheduled\",\"op3\":\"IFR\"}",
            pic_flying: nil,
            pic_to: nil,
            day_to: nil,
            pic_instrument_approach: nil,
            instrument_approach_info: nil,
            pic_ld: nil,
            day_ld: nil,
            landing_dist_reqd: nil,
            landing_dist_avail: nil,
            dispatch_msg: nil,
            fms_ident: "FPL-GBB134-IS -A320/M-SDGHIRWY/S -FACT1700 -N0439F390 TETAN1A TETAN UZ2 NIBEX NIBEX2A -FAOR0129 FALA -PBN/A1B1L1O1S1S2 DOF/240611 REG/ZSGAO EET/FAJA0037 OPR/GLOBAL AVIATION 0027825689347 RMK/SARNML",
            dep_cat: nil,
            dest_cat: "250/287/M78 ",
            alt1_cat: "CI025",
            alt2_cat: "M78/291/250 ",
            toalt_cat: nil,
            hora_departure: 192374,
            hora_arrival: 12342513,
            alt2AsInfoOnly: false, // Boolean represented as 0 in MySQL
            atc_ctot: "FACT RWY-19 TETAN1A TETAN UZ2 NIBEX NIBEX2A RWY-03R FAOR FACT/FL390",
            ctot_updated_at: nil,
            times_ctot: DateTimeFunctions.stringToDate("2024-06-11 17:10:00"),
            eta: DateTimeFunctions.stringToDate("2024-06-11 18:49:00"),
            delay_codes: nil,
            times_off: DateTimeFunctions.stringToDate("2024-06-11 17:10:00"),
            times_on: DateTimeFunctions.stringToDate("2024-06-11 18:39:00"),
            times_blk: nil,
            times_airb: nil,
            times_land: nil,
            times_flt: nil,
            landing_cycles: nil,
            aircraft_cycles_pre_flight: nil,
            ttsn: nil,
            atc_route: "FACT RWY-19 TETAN1A TETAN UZ2 NIBEX NIBEX2A RWY-03R FAOR FACT/FL390",
            atc_status: nil,
            route_fir_trans: nil,
            route_climb: nil,
            route_cruise: nil,
            route_descend: nil,
            route_hold: nil,
            aircraft_cruise_profiles: nil,
            route_distance: 618,
            route_gcd: 686,
            route_ratio: 0.900874635569,
            route_fl: 390,
            route_fl_min: 390,
            route_fl_max: 390,
            route_tt_avg: nil,
            route_wv_vcomp: 78,
            enroute_text: nil,
            temp_toc: -57,
            to_airport: "FACT",
            to_settings: "[]",
            ld_airport: "FAOR",
            engine_time: nil,
            ld_settings: "[]",
            oil_uplift_left: nil,
            oil_uplift_center: nil,
            oil_uplift_right: nil,
            oil_uplift_apu: nil,
            prist_litres_uplift: nil,
            fuel_trip: 7929,
            fuel_trip_time: 5340,
            fuel_taxi: 400,
            fuel_taxi_time: 600,
            fuel_cont: 396,
            fuel_cont_time: 300,
            fuel_cont_pct: nil,
            fuel_alt1: 2351,
            fuel_alt1_time: 1380,
            fuel_alt2: nil,
            fuel_alt2_time: nil,
            fuel_hold: 2093,
            fuel_hold_time: 1800,
            fuel_comp: 31,
            fuel_comp_time: 0,
            fuel_ramp_min: nil,
            fuel_additional: nil,
            fuel_holding: nil,
            fuel_holding_time: nil,
            fuel_comp_extra: nil,
            fuel_comp_extra_time: nil,
            fuel_additional_time: nil,
            fuel_extra: nil,
            fuel_extra_time: nil,
            fuel_ramp: nil,
            fuel_ramp_time: nil,
            fuel_extra_corrected: nil,
            fuel_discretionary: nil,
            fuel_required: 96521,
            fuel_dest_min: 0,
            fuel_ld: 96521,
            touchdown_weight: 134481,
            fuel_gain_loss: "",
            fuel_correction: nil,
            fuel_last_flight: 109321,
            fuel_burned_before_uplift: 150127,
            fuel_before_uplift: nil,
            fuel_uplift: 101392,
            fuel_ramp_actual: 142198,
            fuel_burned_after_uplift: nil,
            fuel_engine_on: nil,
            fuel_take_off: nil,
            fuel_burned_engine: nil,
            fuel_on_block: nil,
            fuel_burned_after_engineoff: nil,
            fuel_after_flight: nil,
            fuel_burned_total: nil,
            fuel_trip_actual: nil,
            fuel_ramp_max: nil,
            fuel_type: nil,
            fuel_density: 0.8040,
            remark_extra_fuel_consumption: nil,
            reason_extra_fuel: nil,
            reason_additional_fuel: nil,
            reason_tech_log_change: nil,
            pax: 0,
            pax_male: 0,
            pax_female: 0,
            pax_child: 0,
            pax_infant: 0,
            dest2: nil,
            dest3: nil,
            pax_qty_dest1: nil,
            pax_qty_dest2: nil,
            pax_qty_dest3: nil,
            weight_pax: 96521,
            weight_cargo: 0,
            weight_bo: 96521,
            weight_payload: 134481,
            weight_zf: nil,
            weight_zf_max: nil,
            weight_ramp: 113021,
            weight_ramp_max: 152820,
            weight_to: nil,
            weight_to_max: 102399,
            weight_to_max_regulated: 142198,
            weight_ld: nil,
            weight_ld_max: nil,
            weight_ld_max_regulated: nil,
            fir_list: "[]",
            adequate_airport_list: "[\"FACT\",\"FAOR\"]",
            alternate_airport_list: "[]",
            weather_updated_at: DateTimeFunctions.stringToDate("0000-00-00 00:00:00") ?? Date(),
            documents_updated_at: nil,
            sid_procedure: "TETA1A",
            star_procedure: "NIBE2A",
            app_config: nil,
            change_log: nil,
            created_at: DateTimeFunctions.stringToDate("2024-06-11 06:07:10"),
            updated_at: DateTimeFunctions.stringToDate("2024-06-11 06:07:11")
        ),
        
        FlightDataDB(
            id: 400025,
            flight_id: 500030,
            route: 32,
            user_remarks: "",
            icfa_remarks: "",
            technical_log_no: "",
            sign_date: DateTimeFunctions.stringToDate("2024-02-12 17:05:00") ?? nil,
            pic_sign_date: nil,
            sign_by_pin: false, // Boolean represented as 0 in MySQL
            security_search_check: nil,
            check_cat_2: nil,
            successfull_cat_2: nil,
            unsuccessfull_cat_2: nil,
            flight_plan_id: "3966",
            dispatcher: "",
            gufi: "GSW-ENT-OC1",
            aircraft_config: "b3cda885-5ae1-4aab-bff1-4045b492c790",
            operations_type: "{\"op1\":\"Scheduled\",\"op3\":\"IFR\"}",
            pic_flying: true,
            pic_to: true,
            day_to: false,
            pic_instrument_approach: nil,
            instrument_approach_info: "",
            pic_ld: true,
            day_ld: false,
            landing_dist_reqd: 0,
            landing_dist_avail: nil,
            dispatch_msg: "",
            fms_ident: "",
            dep_cat: "B",
            dest_cat: "B",
            alt1_cat: "B",
            alt2_cat: "",
            era_cat: "",
            toalt_cat: "",
            hora_departure: nil,
            hora_arrival: nil,
            alt2AsInfoOnly: true, // Boolean represented as 1 in MySQL
            atc_ctot: "B",
            ctot_updated_at: DateTimeFunctions.stringToDate("2024-02-12 17:05:00") ?? nil,
            times_ctot: DateTimeFunctions.stringToDate("2024-02-12 17:05:00") ?? nil,
            eta: DateTimeFunctions.stringToDate("2024-02-12 18:58:04") ?? nil,
            delay_codes: "[{\"id\":\"89\",\"time\":300,\"code_id\":\"AM\",\"sub_code\":\"\",\"code_name\":\"Restrictions at airport of departure\",\"code_description\":\"Including air traffic services, start-up and pushback, airport and\\/or runway closed due to obstruction or weather (restriction due to weather in case of ATFM only) industrial action, staff shortage, political unrest, noise abatement, night curfew, special flights.\"}]', '2024-02-12 17:10:33', '2024-02-12 19:06:04', 116, '2024-02-12 17:19:41', '2024-02-12 18:53:51', 94, 1, 0, NULL, 'DEGES Z2 TUNUM Z204 GEDSO DCT VEKEN DCT RINAV DCT ARBER', 'PBN/B2B3B4B5D1S2A1 DOF/240212 REG/HBJOK EET/LOVV0009 \nEDMM0012 LOVV0015 LIMM0025 LOVV0026 LIMM0032 LJLA0034 \nLDZO0043 LQSB0050 LYBA0110 LAAA0117 LYBA0129 SEL/AQGM \nCODE/4B193A RVR/75 OPR/GSW RMK/NOISE CHAPTER 4 OCC CONTACT \n0041445102271', '', '250/CI8', 'CI 80', 'CI8/250', 'GREEN DOT', '[\"CI 0\",\"CI 80\",\"CI 20\",\"CI 40\",\"CI 60\",\"CI 100\"]",
            times_off: DateTimeFunctions.stringToDate("2024-02-12 17:05:00") ?? nil,
            times_on: DateTimeFunctions.stringToDate("2024-02-12 18:58:04") ?? nil,
            times_blk: nil,
            times_airb: nil,
            times_land: nil,
            times_flt: nil,
            landing_cycles: nil,
            aircraft_cycles_pre_flight: nil,
            ttsn: nil,
            atc_route: "B",
            atc_status: "B",
            route_fir_trans: "B",
            route_climb: "",
            route_cruise: "",
            route_descend: "",
            route_hold: "",
            aircraft_cruise_profiles: "",
            route_distance: 716,
            route_gcd: 604,
            route_ratio: 0.0,
            route_fl: 390,
            route_fl_min: 330,
            route_fl_max: 330,
            route_tt_avg: 115,
            route_wv_vcomp: 31,
            enroute_text: "",
            temp_toc: -6,
            to_airport: "LSZH",
            to_settings: "{\"deicing_holdover_time\":\"\",\"deicing_start_time\":\"\",\"deicing_volume_step1\":\"\",\"deicing_volume_step2\":\"\",\"deicing_supplier\":\"\",\"deicing_receiptNo\":\"\",\"deicing_type\":\"\",\"deicing_type_step2\":\"\",\"deicing_mixture\":\"\",\"deicing_mixture_step2\":\"\",\"to_anti_ice\":0,\"to_eng_air\":\"0\",\"to_flaps\":\"\",\"to_stab_trim\":\"0\",\"to_n1_ref_redu_flex\":\"\",\"to_torque_max\":\"0\",\"to_reduced_torque\":\"0\",\"climb_reduced_torque\":\"0\",\"climb_torque_max\":\"0\",\"to_toga\":\"\",\"to_flex\":\"\",\"to_flex_temp\":\"\",\"to_n1\":\"\",\"to_rpm\":\"\",\"to_torque\":\"\",\"to_trim\":\"\",\"to_thrust_mode\":\"\",\"to_pitch\":\"\",\"gross_climb\":\"0\",\"to_engine_pressure_ratio\":\"0\",\"acceleration\":\"0.00\",\"nadp\":\"\",\"to_acceleration_altitude\":\"\",\"to_se_acc\":\"\",\"acceleration_altitude\":\"(null)\",\"to_glide\":\"\",\"take_off_values\":[],\"to_configuration\":\"\",\"to_v1\":\"\",\"to_venr\":\"0\",\"to_vmhb\":0,\"to_vmlb\":0,\"to_vr\":\"\",\"to_vg\":\"\",\"to_v2_flaps_9_15\":\"\",\"to_v2_flaps_0\":\"\",\"to_v4\":\"\",\"to_vyse\":\"\",\"to_vy\":\"\",\"to_vx\":\"\",\"to_v2\":\"\",\"to_vfto\":\"\",\"to_vfs\":\"\",\"to_vref\":\"\",\"to_vac\":\"\",\"to_vfr\":\"\",\"to_vft\":\"\",\"to_v_emg\":\"\",\"to_type\":\"\",\"to_ge\":\"\",\"to_setting\":\"\",\"to_heater\":\"\",\"to_eaps\":\"\",\"to_ibf\":\"\",\"to_dist_required\":\"\",\"to_dist_available\":\"\",\"to_Epr\":\"\",\"to_vse\":\"\",\"to_mode\":\"\",\"to_breaking_action_1\":\"\",\"to_breaking_action_2\":\"\",\"to_breaking_action_3\":\"\",\"to_coverage_1\":\"\",\"to_coverage_2\":\"\",\"to_coverage_3\":\"\",\"to_depth_1\":\"\",\"to_depth_2\":\"\",\"to_depth_3\":\"\",\"to_type_1\":\"\",\"to_type_2\":\"\",\"to_type_3\":\"\",\"to_cleared_width\":\"\"}",
            ld_airport: "BKPR",
            engine_time: 0,
            ld_settings:"{\"ld_flaps\":\"\",\"ld_anti_ice\":0,\"ld_vref\":\"\",\"ld_vapp\":\"\",\"ld_ga_rpm\":0,\"ld_dist\":\"\",\"ld_weight_arrival\":\"0\",\"ld_eng_air\":\"0\",\"ld_ga_torque\":\"\",\"ld_toga\":\"\",\"landing_values\":[],\"ld_configuration\":\"\",\"ld_v2_flaps_0\":\"\",\"ld_v2_flaps_9\":\"\",\"ld_vac\":\"\",\"ld_vfs\":\"0\",\"ld_vga\":0,\"ld_vmhb\":0,\"ld_vmlb\":0,\"ld_vfto\":\"\",\"ld_vma\":\"\",\"ld_vyse\":\"\",\"ld_vapl\":\"\",\"no_change_at_dest\":\"\",\"dispatchers_criteria_correct\":\"\",\"ldta_calc\":\"\",\"ldta\":\"\",\"factorised_landing_dist\":\"\",\"ld_reverse\":\"\",\"ld_breaking_action_1\":\"\",\"ld_breaking_action_2\":\"\",\"ld_breaking_action_3\":\"\",\"ld_coverage_1\":\"\",\"ld_coverage_2\":\"\",\"ld_coverage_3\":\"\",\"ld_depth_1\":\"\",\"ld_depth_2\":\"\",\"ld_depth_3\":\"\",\"ld_type_1\":\"\",\"ld_type_2\":\"\",\"ld_type_3\":\"\",\"ld_cleared_width\":\"\",\"ld_ice_acc\":null}",
            oil_uplift_left: 9940,
            oil_uplift_center: 6000,
            oil_uplift_right: 305,
            oil_uplift_apu: 720,
            prist_litres_uplift: 497,
            fuel_trip: 300,
            fuel_trip_time: 5,
            fuel_taxi: 2723,
            fuel_taxi_time: 1680,
            fuel_cont: 0,
            fuel_cont_time: 0,
            fuel_cont_pct: "2338",
            fuel_alt1: 1800,
            fuel_alt2: 15803,
            fuel_hold: 0,
            fuel_hold_time: 0,
            fuel_comp: 7244,
            fuel_comp_time: 5760,
            fuel_ramp_min: 23047,
            fuel_additional: 16260,
            fuel_holding: 0,
            fuel_holding_time: 0,
            fuel_comp_extra: 0,
            fuel_comp_extra_time: 0,
            fuel_additional_time: 25269,
            fuel_extra: 10538,
            fuel_extra_time: 15036,
            fuel_ramp: 13537,
            fuel_ramp_time: 15036,
            fuel_extra_corrected: 24075,
            fuel_discretionary: 10087,
            fuel_required: 41897,
            fuel_dest_min: 123,
            fuel_ld: 12323,
            touchdown_weight: 123134,
            fuel_gain_loss: "",
            fuel_correction: "",
            fuel_last_flight: nil,
            fuel_burned_before_uplift: 30037,
            fuel_before_uplift: 5159,
            fuel_uplift: 95301,
            fuel_ramp_actual: 35196,
            fuel_burned_after_uplift: 130498,
            fuel_engine_on: 137788,
            fuel_take_off: 156072,
            fuel_burned_engine: 166754,
            fuel_on_block: 155767,
            fuel_burned_after_engineoff: 166449,
            fuel_after_flight: 0,
            fuel_burned_total: 145680,
            fuel_trip_actual: 145505,
            fuel_ramp_max: 0,
            fuel_type: "Jet A-1",
            fuel_density: 0.8000,
            remark_extra_fuel_consumption: "",
            reason_extra_fuel: "",
            reason_additional_fuel: "",
            reason_tech_log_change: nil,
            pax: 0,
            pax_male: 0,
            pax_female: 0,
            pax_child: 0,
            pax_infant: 0,
            dest2: "",
            dest3: "",
            pax_qty_dest1: 0,
            pax_qty_dest2: 0,
            pax_qty_dest3: 0,
            weight_pax: 0,
            weight_cargo: 0,
            weight_bo: 0,
            weight_payload: 0,
            weight_zf: 0,
            weight_zf_max: 0,
            weight_ramp: 0,
            weight_ramp_max: 0,
            weight_to: 0,
            weight_to_max: 0,
            weight_to_max_regulated: 0,
            weight_ld: 0,
            weight_ld_max: 0,
            weight_ld_max_regulated: 0,
            fir_list: "[\"LSAS\",\"LOVV\",\"EDMM\",\"LOVV\",\"LIMM\",\"LOVV\",\"LIMM\",\"LJLA\",\"LDZO\",\"LQSB\",\"LYBA\",\"LAAA\",\"LYBA\",\"LWSS\"]",
            adequate_airport_list: "[\"BKPR\",\"EDDM\",\"EDJA\",\"EDNY\",\"LATI\",\"LBSF\",\"LDDU\",\"LDRI\",\"LDSP\",\"LDZA\",\"LDZD\",\"LGTS\",\"LIBR\",\"LJLJ\",\"LOWS\",\"LQSA\",\"LSZH\",\"LWOH\",\"LWSK\",\"LYPG\"]",
            alternate_airport_list: "[\"\"]",
            weather_updated_at: DateTimeFunctions.stringToDate("2024-02-12 15:44:23") ?? Date(),
            documents_updated_at: nil,
            sid_procedure: "DEGE3W: RW28 DEGES3W DEGES",
            star_procedure: "ARBE1C: ARBER ARBER1C RW17",
            app_config:"{\"aircraft_registered\":\"1\",\"all_block_check\":\"0\",\"cargo_load_cb\":\"\",\"fuel_load_cb\":\"\",\"fuelSupplier_dep_dest_segment_index\":\"\",\"fuel_weight_volume_segment_index\":\"\",\"isFuelTakeOffEdited\":\"0\",\"wb_extended\":\"0\",\"techlog_available\":\"1\",\"fuel_min_deprecated\":15498}",
            change_log: "[]",
            created_at: DateTimeFunctions.stringToDate("2024-05-01 07:13:24") ?? nil,
            updated_at: DateTimeFunctions.stringToDate("2024-05-01 07:13:24") ?? nil
        )
    ]
}

       
